In [2]:
import selenium
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.options import Options 
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import re
from io import StringIO
from bs4 import BeautifulSoup
import contextlib
from selenium.common.exceptions import InvalidArgumentException
import time
import pandas as pd
pd.set_option('display.max_rows', 1000)
import math
import os.path
import pickle
import random

# ignore warnings
pd.options.mode.chained_assignment = None

import undetected_chromedriver as uc

from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium_stealth import stealth

# Log In

In [129]:
driver = uc.Chrome(use_subprocess=True)

In [131]:
driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")

In [133]:
def mercari_login(driver, username, password):
    # go to mercari login page
    driver.get('https://www.mercari.com/login/')
    
    # # if cookies have been created, load them
    # if os.path.isfile('mercari_cookies.pkl'):
    #     cookies = pickle.load(open("mercari_cookies.pkl", "rb"))
    #     for cookie in cookies:
    #         driver.add_cookie(cookie)
    
    # click "got it" cookies button if it pops up
    try:
        driver.find_element(By.XPATH, '//*[@id="truste-consent-button"]').click()
    except:
        pass

    # enter username and password
    driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/form/div[3]/input').send_keys(username)
    driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/form/div[6]/input').send_keys(password)
    driver.find_element(By.XPATH, '//*[@id="__next"]/div[1]/main/div/div/form/div[6]/input').send_keys(Keys.RETURN)

    # click SMS login button if it pops up
    time.sleep(1)
    try:
        sms_button = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="MFACode"]')))
        sms_button.click()
        # enter SMS code
        sms_code = input('Enter the login code sent via email/SMS: ')
        sms_input = driver.find_element(By.XPATH, '//*[@data-testid="MFACode"]')
        sms_input.send_keys(sms_code)
        WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="VerifyPhoneMFAButton"]'))).click()
    except:
        pass
    
    # click SMS login button if it pops up
    time.sleep(1)
    try:
        sms_button = WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="VerifyPhoneMFAButton"]')))
        sms_button.click()
        # enter SMS code
        sms_code = input('Enter the login code sent via email/SMS: ')
        sms_input = driver.find_element(By.XPATH, '//*[@data-testid="MFACode"]')
        sms_input.send_keys(sms_code)
        WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="VerifyPhoneMFAButton"]'))).click()
    except:
        pass
    
    
    driver.get('https://www.mercari.com/')
    time.sleep(2)
    
#     if driver.current_url == 'https://www.mercari.com/login/?login_callback=%2Fmypage%2Flistings%2Factive%2F':
#         mercari_login(driver, username, password)
    
#     # dump cookies
#     pickle.dump(driver.get_cookies(), open("mercari_cookies.pkl", "wb"))

In [135]:
mercari_login(driver, 'username', 'password')

Enter the login code sent via email/SMS:

In [136]:
pickle.dump(driver.get_cookies(), open("mercari_cookies.pkl", "wb"))

# Get Current Products

In [15]:
def get_current_products(driver):
    
    # define BeautifulSoup as a global variable ("tell Python that the local one is the same as the global one")
    global BeautifulSoup
    
    # go to active listings
    driver.get('https://www.mercari.com/mypage/listings/active/')
    
    # click "got it" cookies button if it pops up
    try:
        driver.find_element(By.XPATH, '//*[@id="truste-consent-button"]').click()
    except:
        pass
    
    # get page source
    page_source = driver.page_source
    soup = BeautifulSoup(page_source, 'lxml')
    
    # get list of products on page
    from bs4 import BeautifulSoup
    import re

    # empty vectors for variable storage
    links = []
    product_names = []
    prices = []
    dates = []

    for i in range(1, 1000):
        try:
            if i==1:
                driver.get('https://www.mercari.com/mypage/listings/active/')
                WebDriverWait(driver, 1.5).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[4]/main/div/div[3]/div[2]/ul/li[1]/div/div[3]/div/div[1]/a')))
            if i>1:
                driver.get('https://www.mercari.com/mypage/listings/active/?page='+str(i))
                WebDriverWait(driver, 1.5).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[4]/main/div/div[3]/div[2]/ul/li[1]/div/div[3]/div/div[1]/a')))
        except:
            pass

        # update page source
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'lxml')

        # if "No results" is present on the page and no products are found, break loop
        if 'No items for sale' in soup.text and len(soup.find_all(attrs={"class":"Link-sc-us5oxt MenuLink-sc-1k5i400 koA-DLz ehDaPW T2-sc-1pugix3 MetaColumn__T2NoWrapEllipsis-sc-18c8425f-1 dNZGZp bhVasx"}, href=True)) == 0:
            print('No more items left, returning variables.')
            time.sleep(1)
            break

        else:
            # get soups
            product_soup = soup.find_all(attrs={"class" : re.compile('ListingsTable__Title')}, href=True)
            price_soup = soup.find_all(attrs={"name": "price"})
            date_soup = soup.find_all("div", {"class": "Row__RowItem-sc-499eeca5-0 hoZBfq"})

            # get product names and links
            for tag in product_soup:
                link = 'https://mercari.com' + tag.get('href')
                links.append(link)
                p_name = str(tag).split('blank">')[-1].split('<')[0]
                product_names.append(p_name)

            # get product prices
            price_soup = soup.find_all(attrs={"id":"price"})
            for tag in price_soup:
                price = float(re.split('value="|"/>', str(tag))[1])
                prices.append(price)

            # get last time products were updated
            date_soup = soup.find_all("td", attrs={"class":"sc-4f08e2f6-0 hoSepO"})
            for tag in date_soup:
                if "/22" in str(tag) or "/23" in str(tag) or "/24" in str(tag) or "/25" in str(tag):
                    date = str(re.split('>|</td>',str(tag))[1])
                    dates.append(date)
    
    return product_names, links, prices, dates

In [17]:
product_names, links, prices, dates = get_current_products(driver)

No more items left, returning variables.

In [23]:
for x in [product_names, links, prices, dates]:
    print(len(x))

1172
1172
1172
1172

In [25]:
# dataframe w/ prices and items
dict = {'Item': product_names, 'Link': links, 'Price': prices, 'Last Updated': dates} 

df = pd.DataFrame(dict)
display(df)

,Item,Link,Price,Last Updated
0,Shonen Jump Issue 15 April 2004 Yu Gi OH Cover...,https://mercari.com/us/item/m65957477729/,6.99,12/31/24
1,Liquid Death Don't F The Planet Death To Plast...,https://mercari.com/us/item/m86523504539/,9.99,12/30/24
2,Sony RMT-D197A DVD Player Remote Control Teste...,https://mercari.com/us/item/m71278368472/,11.99,12/30/24
3,Sony RM-ADU007 AV System Remote Control Tested...,https://mercari.com/us/item/m98037395870/,9.99,12/30/24
4,Wincraft ESPN U Hanging Plastic Sign 11x17 Alw...,https://mercari.com/us/item/m84785797973/,18.99,12/29/24
...,...,...,...,...
1167,Vintage Street Rodder Magazine March 1993 Volu...,https://mercari.com/us/item/m64574459359/,6.22,08/12/24
1168,Vintage Champion Logo T Shirt Blue Bar Size M ...,https://mercari.com/us/item/m11259306723/,7.20,08/12/24
1169,Bridgestone Firestone Hat Hot Graphic Black Au...,https://mercari.com/us/item/m12440616746/,6.92,08/12/24
1170,Vintage Hawaii Souvenir Hat Black Pink Snap Ba...,https://mercari.com/us/item/m72035723594/,7.06,08/12/24
1171,Vintage Champion T Shirt Size S Blue Tag It Ta...,https://mercari.com/us/item/m27403024224/,9.99,11/14/24

# Identify Listings That Were Sold on Vendoo So They Can Be Deleted From Mercari

In [27]:
active_df = df.copy()

In [29]:
active_df

,Item,Link,Price,Last Updated
0,Shonen Jump Issue 15 April 2004 Yu Gi OH Cover...,https://mercari.com/us/item/m65957477729/,6.99,12/31/24
1,Liquid Death Don't F The Planet Death To Plast...,https://mercari.com/us/item/m86523504539/,9.99,12/30/24
2,Sony RMT-D197A DVD Player Remote Control Teste...,https://mercari.com/us/item/m71278368472/,11.99,12/30/24
3,Sony RM-ADU007 AV System Remote Control Tested...,https://mercari.com/us/item/m98037395870/,9.99,12/30/24
4,Wincraft ESPN U Hanging Plastic Sign 11x17 Alw...,https://mercari.com/us/item/m84785797973/,18.99,12/29/24
...,...,...,...,...
1167,Vintage Street Rodder Magazine March 1993 Volu...,https://mercari.com/us/item/m64574459359/,6.22,08/12/24
1168,Vintage Champion Logo T Shirt Blue Bar Size M ...,https://mercari.com/us/item/m11259306723/,7.20,08/12/24
1169,Bridgestone Firestone Hat Hot Graphic Black Au...,https://mercari.com/us/item/m12440616746/,6.92,08/12/24
1170,Vintage Hawaii Souvenir Hat Black Pink Snap Ba...,https://mercari.com/us/item/m72035723594/,7.06,08/12/24
1171,Vintage Champion T Shirt Size S Blue Tag It Ta...,https://mercari.com/us/item/m27403024224/,9.99,11/14/24

In [31]:
driver.get('https://web.vendoo.co/login/')

In [33]:
# define username and password
username='username'
password='password'

# enter username and password
driver.find_element(By.XPATH, '//*[@id="email"]').send_keys(username)

driver.find_element(By.XPATH, '//*[@id="password"]').send_keys(password)
driver.find_element(By.XPATH, '//*[@id="password"]').send_keys(Keys.RETURN)

In [93]:
driver.get('https://web.vendoo.co/app?status=sold')

In [39]:
# clear sold listing detections
from selenium.webdriver.common.action_chains import ActionChains

try:
    element = driver.find_element(By.XPATH, '//*[@aria-label="Clear All Latest Detection"]')
    actions = ActionChains(driver)
    actions.move_to_element(element)
    actions.perform()
    driver.execute_script('window.scrollBy(0, 100)')
    element.click()
except:
    pass

In [95]:
# scroll down to bottom while allowing time for products to load V2
curr_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
for i in range(0,1000):
    page = driver.find_element("tag name","html")
    page.send_keys(Keys.END)
    time.sleep(0.5)
    new_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
    try:
        driver.find_element(By.XPATH, "/html/body/div[1]/div/div[1]/div/div[3]/div/div/div[1]/div[1]/div[2]/div/div/div[2]/div[1]/div/div[3]/div/div/span/div[2]/div/div")
    except:
        break

In [97]:
# change to 240 items/page
driver.find_element(By.XPATH, '//*[@class="buttons__ButtonDefaultStyled-rvbg1v-10 styles__ItemsPerPageButton-wgdgzp-1 hBjREI buqMst"]').click()
driver.find_element(By.CSS_SELECTOR, '.EESAW > div:nth-child(4)').click()
# driver.find_element(By.XPATH, '//*[@data-testid="dropdown__option__240"]').click()

In [99]:
# scroll down to bottom while allowing time for products to load V2
curr_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
for i in range(0,1000):
    page = driver.find_element("tag name","html")
    page.send_keys(Keys.END)
    time.sleep(0.5)
    new_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
    try:
        driver.find_element(By.XPATH, "/html/body/div[1]/div/div[1]/div/div[3]/div/div/div[1]/div[1]/div[2]/div/div/div[2]/div[1]/div/div[3]/div/div/span/div[2]/div/div")
    except:
        break

In [101]:
page_source = driver.page_source
soup = BeautifulSoup(page_source, 'lxml')

In [103]:
vendoo_df = pd.read_csv('vendoo_sold_products.csv')

In [105]:
vendoo_list = vendoo_df['product'].tolist()

In [117]:
# get sold products from Vendoo
sold_products = []
num_pages = int(re.split('\n', driver.find_element(By.CLASS_NAME, 'rc-pagination').text)[-1])
for i in range(num_pages):
    # scroll to top
    page = driver.find_element("tag name","html")
    page.send_keys(Keys.HOME)
    
    time.sleep(1)
    
    # scroll down
    curr_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
    for i in range(0,100):
        page = driver.find_element("tag name","html")
        page.send_keys(Keys.END)
        time.sleep(0.5)
        new_scrollheight = driver.execute_script("return document.documentElement.scrollHeight")
        if new_scrollheight != curr_scrollheight:
            curr_scrollheight = new_scrollheight
        else:
            break
    
    # wait
    time.sleep(1)
    
    # get products
    page_source = driver.page_source
    soup = BeautifulSoup(page_source, 'lxml')
    page_product_soup = soup.find_all("span",attrs={"class":"styles__HighlightTextStyled-jahwfy-5 fvIvfJ"})
    for tag in page_product_soup:
        # print(tag.text)
        sold_products.append(tag.text)
        if tag.text not in vendoo_list:
            vendoo_list.insert(0, tag.text)
        else:
            print('item already in list of sold items')
            break
    else:
        continue
        print(sold_products[-1],str(len(sold_products)), '\n')
        page.send_keys(Keys.END)
        r_chevron = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '//*[@id="chevron-right"]')))
        r_chevron.click()
        time.sleep(1)
    break

item already in list of sold items

In [119]:
vendoo_df = pd.DataFrame({'product': vendoo_list})

In [123]:
vendoo_df.to_csv('vendoo_sold_products.csv', index=False)

In [127]:
# determine products that are marked as sold on Vendoo but are still active on Mercari
soldlist = []
for i in range(len(active_df)):
    product_name = active_df.iloc[i,0]
    if product_name in vendoo_list:
        soldlist.append(product_name)
        
soldlist_df = pd.DataFrame({'Item':soldlist})
soldlist_df.insert(loc = 1,column = 'Deleted',value = '<input type="checkbox" />')
soldlist_df.style

# Get Products Again After Deleting Sold Listings

In [152]:
product_names, links, prices, dates = get_current_products(driver)

No more items left, returning variables.

In [154]:
for x in [product_names, links, prices, dates]:
    print(len(x))

1181
1181
1181
1181

In [156]:
# dataframe w/ prices and items
dict = {'Item': product_names, 'Link': links, 'Price': prices, 'Last Updated': dates} 

df = pd.DataFrame(dict)
display(df)

,Item,Link,Price,Last Updated
0,Shonen Jump Issue 15 April 2004 Yu Gi OH Cover...,https://mercari.com/us/item/m65957477729/,6.99,12/31/24
1,Liquid Death Don't F The Planet Death To Plast...,https://mercari.com/us/item/m86523504539/,9.99,12/30/24
2,Sony RMT-D197A DVD Player Remote Control Teste...,https://mercari.com/us/item/m71278368472/,11.99,12/30/24
3,Sony RM-ADU007 AV System Remote Control Tested...,https://mercari.com/us/item/m98037395870/,9.99,12/30/24
4,Wincraft ESPN U Hanging Plastic Sign 11x17 Alw...,https://mercari.com/us/item/m84785797973/,18.99,12/29/24
...,...,...,...,...
1176,Vintage Street Rodder Magazine March 1993 Volu...,https://mercari.com/us/item/m64574459359/,6.22,08/12/24
1177,Vintage Champion Logo T Shirt Blue Bar Size M ...,https://mercari.com/us/item/m11259306723/,7.20,08/12/24
1178,Bridgestone Firestone Hat Hot Graphic Black Au...,https://mercari.com/us/item/m12440616746/,6.92,08/12/24
1179,Vintage Hawaii Souvenir Hat Black Pink Snap Ba...,https://mercari.com/us/item/m72035723594/,7.06,08/12/24
1180,Vintage Champion T Shirt Size S Blue Tag It Ta...,https://mercari.com/us/item/m27403024224/,9.99,11/14/24

# Drop Price By a Percentage

In [159]:
from datetime import datetime
df['Last Updated'] = pd.to_datetime(df['Last Updated'])
df['Days Since Updating'] = (datetime.today()-df['Last Updated']).dt.days
display(df)

C:\Users\babow\AppData\Local\Temp\ipykernel_23396\4140236999.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Last Updated'] = pd.to_datetime(df['Last Updated'])

,Item,Link,Price,Last Updated,Days Since Updating
0,Shonen Jump Issue 15 April 2004 Yu Gi OH Cover...,https://mercari.com/us/item/m65957477729/,6.99,2024-12-31,3
1,Liquid Death Don't F The Planet Death To Plast...,https://mercari.com/us/item/m86523504539/,9.99,2024-12-30,4
2,Sony RMT-D197A DVD Player Remote Control Teste...,https://mercari.com/us/item/m71278368472/,11.99,2024-12-30,4
3,Sony RM-ADU007 AV System Remote Control Tested...,https://mercari.com/us/item/m98037395870/,9.99,2024-12-30,4
4,Wincraft ESPN U Hanging Plastic Sign 11x17 Alw...,https://mercari.com/us/item/m84785797973/,18.99,2024-12-29,5
...,...,...,...,...,...
1176,Vintage Street Rodder Magazine March 1993 Volu...,https://mercari.com/us/item/m64574459359/,6.22,2024-08-12,144
1177,Vintage Champion Logo T Shirt Blue Bar Size M ...,https://mercari.com/us/item/m11259306723/,7.20,2024-08-12,144
1178,Bridgestone Firestone Hat Hot Graphic Black Au...,https://mercari.com/us/item/m12440616746/,6.92,2024-08-12,144
1179,Vintage Hawaii Souvenir Hat Black Pink Snap Ba...,https://mercari.com/us/item/m72035723594/,7.06,2024-08-12,144
1180,Vintage Champion T Shirt Size S Blue Tag It Ta...,https://mercari.com/us/item/m27403024224/,9.99,2024-11-14,50

In [161]:
# get rid of recently updated listings
pricedrop_df = df.loc[(df['Days Since Updating'] >= 7) ].reset_index(drop=True)

# sort by price, descending
pricedrop_df = pricedrop_df.sort_values('Price', ascending = False).reset_index(drop=True)

# display dataframe of products to de price dropped
display(pricedrop_df.loc[(pricedrop_df['Price'] > 10) ].reset_index(drop=True))

,Item,Link,Price,Last Updated,Days Since Updating
0,Pair of 2 Technics SB-K25 Floor Speakers 3-Way...,https://mercari.com/us/item/m99784160116/,342.94,2024-12-11,23
1,Panasonic RF-2800 Shortwave AM FM Radio Tested...,https://mercari.com/us/item/m82056945871/,299.99,2024-12-27,7
2,Yamaha R-N301 Stereo Receiver Fully Tested No ...,https://mercari.com/us/item/m13560056978/,249.99,2024-12-27,7
3,Bose 321 GS Series II DVD Home Entertainment S...,https://mercari.com/us/item/m99939566800/,199.99,2024-12-23,11
4,Vintage Claudia Grau Patchwork Blazer Jacket S...,https://mercari.com/us/item/m78376995345/,180.49,2024-12-11,23
5,Set of 2 EPI T/E 70 Speakers Time Energy Serie...,https://mercari.com/us/item/m16213763349/,171.00,2024-12-11,23
6,Vintage Zenith C585W Turntable AM FM Radio Tes...,https://mercari.com/us/item/m81180216486/,169.99,2024-12-19,15
7,Life Like Racing NASCAR Electric Slot Car Cham...,https://mercari.com/us/item/m57823475027/,149.99,2024-12-12,22
8,Royal Retros Vintage Icons Washington Senators...,https://mercari.com/us/item/m81077460745/,126.57,2024-12-11,23
9,Vintage Sawyers Mirascreen Slide Projector Vie...,https://mercari.com/us/item/m21110171190/,99.99,2024-12-10,24
10,Vintage Bullock &amp; Jones Genuine Leather Bo...,https://mercari.com/us/item/m70937561840/,89.99,2024-12-11,23
11,Nerf N Strike Stampede ECS Dart Blaster Tested...,https://mercari.com/us/item/m99217665183/,89.99,2024-12-19,15
12,VTG 90s Meshuggah Head Logo Zip Hoodie Size L ...,https://mercari.com/us/item/m78471404367/,89.99,2024-12-23,11
13,Tackla V Sport Factory Bulls Playstation Hocke...,https://mercari.com/us/item/m40375635970/,87.49,2024-12-11,23
14,Vintage 90s Champion Reverse Weave Sweatshirt ...,https://mercari.com/us/item/m61048111579/,84.99,2024-12-23,11
15,Vintage 1985 Coca Cola Super Bowl XIX 19 Umbre...,https://mercari.com/us/item/m48323445155/,84.87,2024-12-11,23
16,Vintage Sears Electric Power 12 Typewriter In ...,https://mercari.com/us/item/m48622652955/,83.32,2024-12-11,23
17,Verit Industries Model 1030 Speakers Vintage H...,https://mercari.com/us/item/m74218483691/,81.00,2024-12-11,23
18,Sony CDP-C500 CD Player 5 Disc Carousel Change...,https://mercari.com/us/item/m51282103869/,76.00,2024-12-11,23
19,Pioneer PD-M423 CD Player with New Optimus 6 D...,https://mercari.com/us/item/m74581043402/,75.99,2024-12-11,23
20,Soundesign AM FM Stereo Receiver Double Casset...,https://mercari.com/us/item/m95151213633/,71.24,2024-12-11,23
21,Polk Audio PSW120 Powered Subwoofer 90W Tested...,https://mercari.com/us/item/m84930332920/,69.99,2024-12-16,18
22,Reebok Authentic Boston Bruins Milan Lucic Hom...,https://mercari.com/us/item/m51333125790/,69.99,2024-12-23,11
23,Blind Skateboard Complete Checkerboard Graphic...,https://mercari.com/us/item/m14789057846/,64.99,2024-12-12,22
24,In Win BP655 Mini ITX PC Case w/ 200W Power Su...,https://mercari.com/us/item/m31580947500/,64.99,2024-12-18,16
25,MethSydnicate Shaniacidal Twaindencies T Shirt...,https://mercari.com/us/item/m23191890933/,63.17,2024-12-11,23
26,Leisure Suit Larry Love For Sale PC Big Box ON...,https://mercari.com/us/item/m39349510081/,61.74,2024-12-11,23
27,Vintage Reebok Authentic Jason Kidd USA Basket...,https://mercari.com/us/item/m92299635460/,60.74,2024-12-11,23
28,Vintage 70s Battery Operated Large Sound Train...,https://mercari.com/us/item/m38745124011/,59.99,2024-12-12,22
29,Adidas MLS LA Galaxy 2017 Away Jersey Size 2XL...,https://mercari.com/us/item/m15165348410/,59.99,2024-12-09,25
30,Mitchell &amp; Ness Arizona Diamondbacks Randy...,https://mercari.com/us/item/m58488953793/,59.99,2024-12-16,18
31,Sony ICF-CD873 AM FM CD Clock Radio Tested Wor...,https://mercari.com/us/item/m53114455607/,59.99,2024-12-12,22
32,Sony CFD-S33 Portable Stereo Boombox AM FM CD ...,https://mercari.com/us/item/m28406320660/,59.99,2024-12-18,16
33,PUMA X Mr Doodle All Over Print Half Zip Jacke...,https://mercari.com/us/item/m79976981463/,59.99,2024-12-17,17
34,Sony CFD-S22 Portable Stereo Boombox AM FM CD ...,https://mercari.com/us/item/m31881004354/,59.99,2024-12-18,16
35,Nintendo Wii Skylanders Lot 3 Games 3 Portals ...,https://mercari.com/us/item/m82673317876/,56.99,2024-12-11,23
36,Boston Red Sox 2024 Japanese Celebration SGA J...,https://mercari.com/us/item/m23751755282/,55.55,2024-12-11,23
37,Bose SoundDock Digital Music System Speaker Te...,https://mercari.com/us/item/m25798496829/,54.99,2024-12-14,20
38,Hasbro Beyblade Burst Surge Speedstorm Slayer ...,https://mercari.com/us/item/m74796791592/,54.99,2024-12-13,21
39,Canon EOS Rebel S SLR 35mm Film Camera Tested ...,https://mercari.com/us/item/m33369830231/,52.24,2024-12-11,23
40,KNEX Rippin Rocket Roller Coaster Building Set...,https://mercari.com/us/item/m21255277138/,52.08,2024-12-11,23
41,Band Hero Wireless Drum Kit Controller Nintend...,https://mercari.com/us/item/m31435938500/,52.08,2024-12-11,23
42,Arco Dupli Disk Hard Drive Duplicator IDE Port...,https://mercari.com/us/item/m84751240484/,50.63,2024-12-11,23
43,Western Digital 13GB 7200RPM IDE Hard Drive 3....,https://mercari.com/us/item/m72792978607/,50.63,2024-12-11,23
44,VTG New England Patriots 2001 AFC Champs Frame...,https://mercari.com/us/item/m77265348265/,50.00,2024-12-05,29
45,Boston Red Sox Nation Pitchers Framed Photo 13...,https://mercari.com/us/item/m57978955305/,50.00,2024-12-05,29
46,Jon Lester Red Sox No Hitter May 19 2008 Frame...,https://mercari.com/us/item/m81973743664/,50.00,2024-12-05,29
47,Long Live Virgil Abloh T Shirt Size L Blue Whi...,https://mercari.com/us/item/m73700561443/,49.99,2024-12-09,25
48,Colosseum UConn Huskies Basketball Jersey Size...,https://mercari.com/us/item/m21655558107/,49.99,2024-12-09,25
49,Earthgang 2022 Tour T Shirt Size L Double Side...,https://mercari.com/us/item/m13016339656/,49.99,2024-12-17,17
50,Vintage 90s Warner Bros Studio Store Rugby Shi...,https://mercari.com/us/item/m54480988056/,49.99,2024-12-09,25
51,RCA CC439 VHS Camcorder For Parts Tape Error I...,https://mercari.com/us/item/m11686461056/,49.99,2024-12-12,22
52,Reebok On Field Baltimore Ravens Michael Oher ...,https://mercari.com/us/item/m51773157265/,49.99,2024-12-09,25
53,Vintage Bentley 100A Deluxe Black And White Po...,https://mercari.com/us/item/m65367341675/,49.99,2024-12-09,25
54,DC Shoes Black Sabbath Slip On Sneakers Size M...,https://mercari.com/us/item/m60828927350/,48.61,2024-12-11,23
55,Vintage 90s The Territory Ahead Suede Bomber J...,https://mercari.com/us/item/m22526752149/,48.61,2024-12-11,23
56,Vintage 90s The Territory Ahead Suede Bomber J...,https://mercari.com/us/item/m37380984942/,48.61,2024-12-11,23
57,Vintage 1980 Boston Red Sox Burlap Wall Hangin...,https://mercari.com/us/item/m31262427088/,47.49,2024-12-11,23
58,Cariuma Oca Low Men Size 9 Green Canvas Skate ...,https://mercari.com/us/item/m37284374943/,47.49,2024-12-11,23
59,Videoke VMP-9000 Karaoke Music Player VCD Test...,https://mercari.com/us/item/m77939325225/,47.12,2024-12-11,23
60,Vintage RCA Color Video Camera CC004 Untested ...,https://mercari.com/us/item/m50823835379/,46.87,2024-12-11,23
61,VTG 1972 Aurora Skittle Pool Tabletop Billiard...,https://mercari.com/us/item/m55673026021/,46.57,2024-12-11,23
62,DJ Absolut The Heart Of New York Rap Cassette ...,https://mercari.com/us/item/m20941457122/,45.56,2024-12-11,23
63,Cutmaster C Cut Vs The World Cassette Mixtape ...,https://mercari.com/us/item/m12710073678/,45.56,2024-12-11,23
64,The Pack AD Long Sleeve Baseball Tee Size L Wh...,https://mercari.com/us/item/m86388253760/,45.12,2024-12-11,23
65,Authentic Nike New England Patriots NFL 100 Ye...,https://mercari.com/us/item/m81485306605/,45.00,2024-12-11,23
66,Lot of 32 Boston Red Sox Pendants 2005 Pendant...,https://mercari.com/us/item/m82715818136/,44.99,2024-12-05,29
67,Samsung PS-WK450 Subwoofer Only Tested Working...,https://mercari.com/us/item/m34494673350/,44.99,2024-12-19,15
68,Worcester Red Sox Woo Sox Smiley Ball Bobblehe...,https://mercari.com/us/item/m66489019504/,42.99,2024-12-12,22
69,Vintage Big Royal View 35mm Film Camera Tested...,https://mercari.com/us/item/m59490454857/,42.86,2024-12-11,23
70,"Element TWIGS Tosh Townend 7"" Complete Skatebo...",https://mercari.com/us/item/m51880778460/,42.84,2024-12-11,23
71,CapTel 2400iBT Ultratec Captioned Hearing Impa...,https://mercari.com/us/item/m71606274524/,41.66,2024-12-11,23
72,Vintage 90s Nike Reversible Jacket Size XL Fle...,https://mercari.com/us/item/m53224129124/,41.66,2024-12-11,23
73,Vintage LL Bean Mountain Guide Gore Tex Jacket...,https://mercari.com/us/item/m22114420124/,40.60,2024-12-11,23
74,Coldplay Rainbow Spellout Bucket Hat OSFA Blac...,https://mercari.com/us/item/m32138406958/,39.99,2024-12-17,17
75,Focusrite iTrack Studio Monitoring Headphones ...,https://mercari.com/us/item/m34091739658/,39.99,2024-12-13,21
76,Reebok Duffle Bag Purple Black Straps Nylon Vi...,https://mercari.com/us/item/m74146752560/,38.57,2024-12-11,23
77,VTG New England Patriots 2001 AFC Champions Ha...,https://mercari.com/us/item/m60849989025/,37.99,2024-12-11,23
78,Mitchell &amp; Ness Denver Nuggets Alex Englis...,https://mercari.com/us/item/m51897332237/,37.97,2024-12-11,23
79,MLB Boston Red Sox Full Zip Jacket Size 2XL Re...,https://mercari.com/us/item/m25181064069/,37.49,2024-12-11,23
80,CROM ILLUSTRATION OOF Coach Jacket Size M Butt...,https://mercari.com/us/item/m15744264697/,37.49,2024-12-11,23
81,Sylvan Esso Shaking Out The Numb Tour Long Sle...,https://mercari.com/us/item/m75215671240/,36.09,2024-12-11,23
82,Vintage Champion Authentic Vince Carter USA Ba...,https://mercari.com/us/item/m39036983322/,35.43,2024-12-11,23
83,All American Collection Georgetown Allen Ivers...,https://mercari.com/us/item/m26304687408/,35.43,2024-12-11,23
84,Minecraft Ender Dragon Mask Plastic Wearable L...,https://mercari.com/us/item/m66223852932/,34.99,2024-12-17,17
85,Vintage Compco Reflex 620 TLR Film Camera With...,https://mercari.com/us/item/m12199070929/,34.99,2024-12-27,7
86,Reebok ATR Chill Sneakers Mens Size 9.5 White ...,https://mercari.com/us/item/m69482000582/,34.99,2024-12-14,20
87,Vintage Bell System Western Electric Rotary Te...,https://mercari.com/us/item/m40044154512/,34.99,2024-12-27,7
88,Sony Dream Machine ICF-CS10ip Alarm Clock AM F...,https://mercari.com/us/item/m51032125701/,34.99,2024-12-14,20
89,Lowerclass Brats Just Like Clockwork T Shirt S...,https://mercari.com/us/item/m34618306727/,34.72,2024-12-11,23
90,DJ G Brown Like A Breath Of Fresh Air Promo CD...,https://mercari.com/us/item/m74969049943/,34.72,2024-12-11,23
91,Vintage 80s Fisher Price Nursery Monitor In Bo...,https://mercari.com/us/item/m77230510419/,34.72,2024-12-11,23
92,Callaway Opti Dri Golf Polo Shirt Size XL New ...,https://mercari.com/us/item/m89126274045/,34.72,2024-12-11,23
93,DJ Doggtime The Art Of Blending Promo Mixtape ...,https://mercari.com/us/item/m71802941774/,34.72,2024-12-11,23
94,Majestic Boston Red Sox Daisuke Matsuzaka Spri...,https://mercari.com/us/item/m18263233349/,34.72,2024-12-11,23
95,Vintage Columbia Sportswear Bugaboo Jacket Men...,https://mercari.com/us/item/m54991263692/,34.72,2024-12-11,23
96,General Electric AM FM Stereo Cassette Recorde...,https://mercari.com/us/item/m49989726123/,34.29,2024-12-11,23
97,The Craft VHS 1996 Fairuza Balk Robin Tunney N...,https://mercari.com/us/item/m27950372921/,33.99,2024-12-19,15
98,Golf Nintendo NES CIB Complete Tested Working ...,https://mercari.com/us/item/m32122473636/,33.74,2024-12-11,23
99,Vintage Snowboard Boots Size 9 Blue Gray Nubuc...,https://mercari.com/us/item/m41370365909/,33.74,2024-12-11,23
100,Fellowes CD Tower 75 Disc Capacity New Sealed NOS,https://mercari.com/us/item/m76602281173/,33.74,2024-12-11,23
101,VTG New Era Goo Goo Dolls 4th of July 2004 Buf...,https://mercari.com/us/item/m31040897605/,33.74,2024-12-11,23
102,Star Trek 25th Anniversary Nintendo Game Boy B...,https://mercari.com/us/item/m69025609636/,33.24,2024-12-11,23
103,Adidas New Zealand All Blacks Rugby Ball White...,https://mercari.com/us/item/m55205329848/,33.24,2024-12-11,23
104,VTG Tudor Mickey Mouse Electric Treasure Hunt ...,https://mercari.com/us/item/m43910192023/,32.59,2024-12-11,23
105,Vintage Riesen Chocolate Chew Duffle Bag Black...,https://mercari.com/us/item/m75915965453/,32.59,2024-12-11,23
106,Rugby World Cup 2011 Australia Jersey Size L W...,https://mercari.com/us/item/m65798390075/,32.57,2024-12-11,23
107,MLB St Louis Cardinals Lars Nootbaar Noot Nick...,https://mercari.com/us/item/m10639320640/,31.58,2024-12-11,23
108,Reebok Classics Question Mid Michigan State Sn...,https://mercari.com/us/item/m12029651542/,30.94,2024-12-11,23
109,Ride Snowboards Orion Snowboard Boots Size Wom...,https://mercari.com/us/item/m65793281406/,30.37,2024-12-11,23
110,Adidas Golden State Warriors Kevin Durant Shor...,https://mercari.com/us/item/m41268212199/,30.37,2024-12-11,23
111,USA Hockey Exclusive Collection Sleeveless Jer...,https://mercari.com/us/item/m42193555424/,30.37,2024-12-11,23
112,JuJuBe Paisley Floral Pattern Backpack Diaper ...,https://mercari.com/us/item/m96015505453/,30.27,2024-12-11,23
113,CASE ONLY For Sony Video8 Camcorder CCD-V5 CCD...,https://mercari.com/us/item/m23183292078/,30.00,2024-12-12,22
114,The North Face Heritage Patch Crewneck Sweatsh...,https://mercari.com/us/item/m47702788486/,29.99,2024-12-09,25
115,Puma Maccabi Tel Aviv 2010-11 Home Soccer Jers...,https://mercari.com/us/item/m47169585146/,29.99,2024-12-11,23
116,GPX Model A2935 Personal Cassette Player AM FM...,https://mercari.com/us/item/m52292923769/,29.99,2024-12-12,22
117,Boston Red Sox 2004 World Series Champs T Shir...,https://mercari.com/us/item/m71753031921/,29.99,2024-12-17,17
118,Nike Sportswear Love And Peace T Shirt Size 2X...,https://mercari.com/us/item/m21627822666/,29.99,2024-12-09,25
119,Vintage Sony ICF-34 AM FM TV Weather Radio Ful...,https://mercari.com/us/item/m46463278658/,29.99,2024-12-27,7
120,Marine Corps University Quang Tri Campus Sweat...,https://mercari.com/us/item/m66986312102/,29.99,2024-12-09,25
121,Uniqlo UT Archive Metal Gear Solid 2 T Shirt S...,https://mercari.com/us/item/m84557412657/,29.77,2024-12-11,23
122,VTG 90s Coca Cola Refreshing Races Hat Flag Em...,https://mercari.com/us/item/m75436103002/,28.49,2024-12-11,23
123,Nickelodeon Rugrats Lookie Cookies 3D Balancin...,https://mercari.com/us/item/m63412685961/,28.49,2024-12-11,23
124,Vintage 90s Washington Capitals Eastern Confer...,https://mercari.com/us/item/m47914494537/,28.12,2024-12-11,23
125,Vintage Champion Reverse Weave Pullover Sweats...,https://mercari.com/us/item/m36138337006/,28.12,2024-12-11,23
126,VTG 80s AT&amp;T Model 6500 Portable Electric ...,https://mercari.com/us/item/m97890638764/,28.12,2024-12-11,23
127,OEM Subaru Outback 2016 2017 2018 Floor Mats B...,https://mercari.com/us/item/m62224170135/,28.12,2024-12-11,23
128,Reeses Peanut Butter Cups Hoodie Size L Orange...,https://mercari.com/us/item/m40494143019/,27.99,2024-12-17,17
129,Champion Reverse Weave Hoodie Size L Script Lo...,https://mercari.com/us/item/m33478373687/,27.99,2024-12-09,25
130,VTG 90s New England Cape Cod Cranberry T Shirt...,https://mercari.com/us/item/m82303510293/,27.99,2024-12-17,17
131,Vintage Jerzees New England Patriots Football ...,https://mercari.com/us/item/m98369945712/,27.99,2024-12-17,17
132,Kawasaki AV1000 Home Theater System AV Switche...,https://mercari.com/us/item/m63097141058/,27.94,2024-12-11,23
133,VTG Tonka Tote Deluxe Racing Set Boxed Mostly ...,https://mercari.com/us/item/m84812679504/,27.94,2024-12-11,23
134,New England Patriots Zubaz Hoodie Size L New W...,https://mercari.com/us/item/m77161673734/,27.77,2024-12-11,23
135,Nike Venture Runner Sneakers Mens Size 13 Ratt...,https://mercari.com/us/item/m68764438306/,27.77,2024-12-11,23
136,Sean John Velour Track Jacket Size 2XLT Black ...,https://mercari.com/us/item/m14955323689/,27.77,2024-12-11,23
137,Nike Flight Retro Windbreaker Jogger Track Pan...,https://mercari.com/us/item/m19385695153/,27.77,2024-12-11,23
138,Jeep Travel Equipment Quarter Zip Sweatshirt S...,https://mercari.com/us/item/m69141132103/,27.77,2024-12-11,23
139,Vintage 80s East West Pullover Ski Jacket Size...,https://mercari.com/us/item/m36467222471/,27.77,2024-12-11,23
140,Reebok NFL Super Bowl XXXVIII 38 Adjustable Ha...,https://mercari.com/us/item/m83354917654/,27.77,2024-12-11,23
141,Vintage Champion Pullover Windbreaker Size L V...,https://mercari.com/us/item/m35653085469/,27.07,2024-12-11,23
142,Nicki Minaj PInk Friday 2 T Shirt Size L White...,https://mercari.com/us/item/m32236722443/,26.99,2024-12-17,17
143,Godsmack 2018 T Shirt Size XL Bostons Own Est ...,https://mercari.com/us/item/m62860318690/,26.99,2024-12-17,17
144,Links Crossbow Training Nintendo Wii Zapper an...,https://mercari.com/us/item/m64853534827/,26.60,2024-12-11,23
145,Vintage 2001 Old School Ball Park Baseball Gam...,https://mercari.com/us/item/m91771144096/,26.46,2024-12-11,23
146,Pair of 2 Sharp CP-C333 Speakers Left and Righ...,https://mercari.com/us/item/m33729572890/,25.72,2024-12-11,23
147,Vintage 90s Home Smart Home Hat Adjustable Str...,https://mercari.com/us/item/m85335324174/,25.57,2024-11-29,35
148,Zubaz Syracuse University Drawstring Pants Siz...,https://mercari.com/us/item/m96047309956/,25.31,2024-12-11,23
149,Adidas All Over Print Logo Hoodie Size M Black...,https://mercari.com/us/item/m67805869265/,25.26,2024-12-11,23
150,Retro Brand Pawtucket Red Sox PawSox Sweatshir...,https://mercari.com/us/item/m55707364569/,25.26,2024-12-11,23
151,Drake Vs Lil Wayne 2014 Tour Dates T Shirt Siz...,https://mercari.com/us/item/m42854259160/,25.26,2024-12-11,23
152,LL Bean Unisex Geometric Fleece Pullover Half ...,https://mercari.com/us/item/m31221440090/,25.26,2024-12-11,23
153,Adidas New England Revolution Soft Shell Bombe...,https://mercari.com/us/item/m19843529710/,25.26,2024-12-11,23
154,RCA Personal Portable Cassette Player Recorder...,https://mercari.com/us/item/m38045418483/,24.99,2024-12-21,13
155,Chassis Grip Block ONLY For Sony CCD-V5 V50 Se...,https://mercari.com/us/item/m85797597309/,24.99,2024-12-12,22
156,Adidas Boston Celtics Kevin Garnett Jersey Siz...,https://mercari.com/us/item/m14589038561/,24.99,2024-12-23,11
157,Charlie Daniels Band Red White And Blue Logo T...,https://mercari.com/us/item/m76350465928/,24.99,2024-12-27,7
158,CNN Plus Half Zip Collared Sweatshirt Size XL ...,https://mercari.com/us/item/m34481939757/,24.99,2024-12-09,25
159,Bravado Black Sabbath Vol 4 T Shirt Size XL Bl...,https://mercari.com/us/item/m64047913730/,24.99,2024-12-17,17
160,New England Patriots Super Bowl XXXIX Champs S...,https://mercari.com/us/item/m53451772207/,24.99,2024-12-11,23
161,Lot of 5 Minnesota Twins 1991 Season Plastic C...,https://mercari.com/us/item/m28522393636/,24.99,2024-12-13,21
162,Vintage 80s Adidas Nylon Windbreaker Pants Siz...,https://mercari.com/us/item/m64184345674/,24.99,2024-12-11,23
163,PING Collection Golf Sweater Mens Size XL Ligh...,https://mercari.com/us/item/m40527571023/,24.99,2024-12-16,18
164,New England Patriots Coors Light 36 Pack Coole...,https://mercari.com/us/item/m18387248083/,24.99,2024-12-21,13
165,Thrasher Magazine Flame Logo Hoodie Size M Nav...,https://mercari.com/us/item/m99367838950/,24.99,2024-12-09,25
166,The Clapper Star Wars Darth Vader Clap Activat...,https://mercari.com/us/item/m11714549409/,24.99,2024-12-13,21
167,RCA Personal Portable Cassette Player Recorder...,https://mercari.com/us/item/m11168613734/,24.99,2024-12-21,13
168,Vintage 90s Puma New England Patriots Hat Snap...,https://mercari.com/us/item/m41643859208/,24.29,2024-12-11,23
169,Vintage 90s Sports Specialties Florida Gators ...,https://mercari.com/us/item/m52257351350/,24.29,2024-12-11,23
170,Vintage 90s Sports Specialties Green Bay Packe...,https://mercari.com/us/item/m81595272244/,24.29,2024-12-11,23
171,Tough Duck Wool Hooded Workwear Jacket Size 3X...,https://mercari.com/us/item/m90993359183/,24.29,2024-12-11,23

In [163]:
def drop_prices(driver, input_df, percent_discount, floor_price):
    input_df = input_df.loc[(input_df['Price'] > floor_price) ].reset_index(drop=True)
    print('Number of items to be discounted:', str(len(input_df)), '\n')
    display(input_df)
    for i in range(0, len(input_df)):
        item = input_df.iloc[i,list(input_df.columns).index('Item')]
        link = input_df.iloc[i,list(input_df.columns).index('Link')]
        curr_price = input_df.iloc[i,list(input_df.columns).index('Price')]
        reduced_price = curr_price - (curr_price * (percent_discount*0.01))
        reduced_price = round(reduced_price, 2)
        # don't drop prices below floor_price
        if reduced_price < floor_price:
            reduced_price = floor_price

        # don't waste time on products already at the floor price    
        if curr_price == reduced_price:
            print('Item '+ str(i+1) + ' of ' + str(len(input_df)), '('+item+')\n', 'Old Price: '+ str(curr_price), 'New Price: '+ str(reduced_price))
            print('\tItem already at floor price.')

        elif curr_price < reduced_price:
            print('Item '+ str(i+1) + ' of ' + str(len(input_df)), '('+item+')\n', 'Old Price: '+ str(curr_price), 'New Price: '+ str(reduced_price))
            print('\tItem already priced below floor price.')

        else:
            print('Item '+ str(i+1) + ' of ' + str(len(input_df)), '('+item+')\n', 'Old Price: '+ str(curr_price), 'New Price: '+ str(reduced_price))
            driver.get(link)
            # click "got it" cookies button if it pops up
            try:
                driver.find_element(By.XPATH, '//*[@id="truste-consent-button"]').click()
            except:
                pass
            time.sleep(1)
            price_element = WebDriverWait(driver, 20).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="price"]')))
            price_element.click()
            price_element.send_keys(Keys.CONTROL + "a");
            price_element.send_keys(Keys.DELETE);
            price_element.send_keys(str(reduced_price))
            price_element.send_keys(Keys.RETURN);
            time.sleep(3)

    print('Done.')
    driver.quit()

In [165]:
# drop_prices(driver, input_df, percent_discount, floor_price)
drop_prices(driver, pricedrop_df, 5, 10)

Number of items to be discounted: 551

,Item,Link,Price,Last Updated,Days Since Updating
0,Pair of 2 Technics SB-K25 Floor Speakers 3-Way...,https://mercari.com/us/item/m99784160116/,342.94,2024-12-11,23
1,Panasonic RF-2800 Shortwave AM FM Radio Tested...,https://mercari.com/us/item/m82056945871/,299.99,2024-12-27,7
2,Yamaha R-N301 Stereo Receiver Fully Tested No ...,https://mercari.com/us/item/m13560056978/,249.99,2024-12-27,7
3,Bose 321 GS Series II DVD Home Entertainment S...,https://mercari.com/us/item/m99939566800/,199.99,2024-12-23,11
4,Vintage Claudia Grau Patchwork Blazer Jacket S...,https://mercari.com/us/item/m78376995345/,180.49,2024-12-11,23
5,Set of 2 EPI T/E 70 Speakers Time Energy Serie...,https://mercari.com/us/item/m16213763349/,171.00,2024-12-11,23
6,Vintage Zenith C585W Turntable AM FM Radio Tes...,https://mercari.com/us/item/m81180216486/,169.99,2024-12-19,15
7,Life Like Racing NASCAR Electric Slot Car Cham...,https://mercari.com/us/item/m57823475027/,149.99,2024-12-12,22
8,Royal Retros Vintage Icons Washington Senators...,https://mercari.com/us/item/m81077460745/,126.57,2024-12-11,23
9,Vintage Sawyers Mirascreen Slide Projector Vie...,https://mercari.com/us/item/m21110171190/,99.99,2024-12-10,24
10,Vintage Bullock &amp; Jones Genuine Leather Bo...,https://mercari.com/us/item/m70937561840/,89.99,2024-12-11,23
11,Nerf N Strike Stampede ECS Dart Blaster Tested...,https://mercari.com/us/item/m99217665183/,89.99,2024-12-19,15
12,VTG 90s Meshuggah Head Logo Zip Hoodie Size L ...,https://mercari.com/us/item/m78471404367/,89.99,2024-12-23,11
13,Tackla V Sport Factory Bulls Playstation Hocke...,https://mercari.com/us/item/m40375635970/,87.49,2024-12-11,23
14,Vintage 90s Champion Reverse Weave Sweatshirt ...,https://mercari.com/us/item/m61048111579/,84.99,2024-12-23,11
15,Vintage 1985 Coca Cola Super Bowl XIX 19 Umbre...,https://mercari.com/us/item/m48323445155/,84.87,2024-12-11,23
16,Vintage Sears Electric Power 12 Typewriter In ...,https://mercari.com/us/item/m48622652955/,83.32,2024-12-11,23
17,Verit Industries Model 1030 Speakers Vintage H...,https://mercari.com/us/item/m74218483691/,81.00,2024-12-11,23
18,Sony CDP-C500 CD Player 5 Disc Carousel Change...,https://mercari.com/us/item/m51282103869/,76.00,2024-12-11,23
19,Pioneer PD-M423 CD Player with New Optimus 6 D...,https://mercari.com/us/item/m74581043402/,75.99,2024-12-11,23
20,Soundesign AM FM Stereo Receiver Double Casset...,https://mercari.com/us/item/m95151213633/,71.24,2024-12-11,23
21,Polk Audio PSW120 Powered Subwoofer 90W Tested...,https://mercari.com/us/item/m84930332920/,69.99,2024-12-16,18
22,Reebok Authentic Boston Bruins Milan Lucic Hom...,https://mercari.com/us/item/m51333125790/,69.99,2024-12-23,11
23,Blind Skateboard Complete Checkerboard Graphic...,https://mercari.com/us/item/m14789057846/,64.99,2024-12-12,22
24,In Win BP655 Mini ITX PC Case w/ 200W Power Su...,https://mercari.com/us/item/m31580947500/,64.99,2024-12-18,16
25,MethSydnicate Shaniacidal Twaindencies T Shirt...,https://mercari.com/us/item/m23191890933/,63.17,2024-12-11,23
26,Leisure Suit Larry Love For Sale PC Big Box ON...,https://mercari.com/us/item/m39349510081/,61.74,2024-12-11,23
27,Vintage Reebok Authentic Jason Kidd USA Basket...,https://mercari.com/us/item/m92299635460/,60.74,2024-12-11,23
28,Vintage 70s Battery Operated Large Sound Train...,https://mercari.com/us/item/m38745124011/,59.99,2024-12-12,22
29,Adidas MLS LA Galaxy 2017 Away Jersey Size 2XL...,https://mercari.com/us/item/m15165348410/,59.99,2024-12-09,25
30,Mitchell &amp; Ness Arizona Diamondbacks Randy...,https://mercari.com/us/item/m58488953793/,59.99,2024-12-16,18
31,Sony ICF-CD873 AM FM CD Clock Radio Tested Wor...,https://mercari.com/us/item/m53114455607/,59.99,2024-12-12,22
32,Sony CFD-S33 Portable Stereo Boombox AM FM CD ...,https://mercari.com/us/item/m28406320660/,59.99,2024-12-18,16
33,PUMA X Mr Doodle All Over Print Half Zip Jacke...,https://mercari.com/us/item/m79976981463/,59.99,2024-12-17,17
34,Sony CFD-S22 Portable Stereo Boombox AM FM CD ...,https://mercari.com/us/item/m31881004354/,59.99,2024-12-18,16
35,Nintendo Wii Skylanders Lot 3 Games 3 Portals ...,https://mercari.com/us/item/m82673317876/,56.99,2024-12-11,23
36,Boston Red Sox 2024 Japanese Celebration SGA J...,https://mercari.com/us/item/m23751755282/,55.55,2024-12-11,23
37,Bose SoundDock Digital Music System Speaker Te...,https://mercari.com/us/item/m25798496829/,54.99,2024-12-14,20
38,Hasbro Beyblade Burst Surge Speedstorm Slayer ...,https://mercari.com/us/item/m74796791592/,54.99,2024-12-13,21
39,Canon EOS Rebel S SLR 35mm Film Camera Tested ...,https://mercari.com/us/item/m33369830231/,52.24,2024-12-11,23
40,KNEX Rippin Rocket Roller Coaster Building Set...,https://mercari.com/us/item/m21255277138/,52.08,2024-12-11,23
41,Band Hero Wireless Drum Kit Controller Nintend...,https://mercari.com/us/item/m31435938500/,52.08,2024-12-11,23
42,Arco Dupli Disk Hard Drive Duplicator IDE Port...,https://mercari.com/us/item/m84751240484/,50.63,2024-12-11,23
43,Western Digital 13GB 7200RPM IDE Hard Drive 3....,https://mercari.com/us/item/m72792978607/,50.63,2024-12-11,23
44,VTG New England Patriots 2001 AFC Champs Frame...,https://mercari.com/us/item/m77265348265/,50.00,2024-12-05,29
45,Boston Red Sox Nation Pitchers Framed Photo 13...,https://mercari.com/us/item/m57978955305/,50.00,2024-12-05,29
46,Jon Lester Red Sox No Hitter May 19 2008 Frame...,https://mercari.com/us/item/m81973743664/,50.00,2024-12-05,29
47,Long Live Virgil Abloh T Shirt Size L Blue Whi...,https://mercari.com/us/item/m73700561443/,49.99,2024-12-09,25
48,Colosseum UConn Huskies Basketball Jersey Size...,https://mercari.com/us/item/m21655558107/,49.99,2024-12-09,25
49,Earthgang 2022 Tour T Shirt Size L Double Side...,https://mercari.com/us/item/m13016339656/,49.99,2024-12-17,17
50,Vintage 90s Warner Bros Studio Store Rugby Shi...,https://mercari.com/us/item/m54480988056/,49.99,2024-12-09,25
51,RCA CC439 VHS Camcorder For Parts Tape Error I...,https://mercari.com/us/item/m11686461056/,49.99,2024-12-12,22
52,Reebok On Field Baltimore Ravens Michael Oher ...,https://mercari.com/us/item/m51773157265/,49.99,2024-12-09,25
53,Vintage Bentley 100A Deluxe Black And White Po...,https://mercari.com/us/item/m65367341675/,49.99,2024-12-09,25
54,DC Shoes Black Sabbath Slip On Sneakers Size M...,https://mercari.com/us/item/m60828927350/,48.61,2024-12-11,23
55,Vintage 90s The Territory Ahead Suede Bomber J...,https://mercari.com/us/item/m22526752149/,48.61,2024-12-11,23
56,Vintage 90s The Territory Ahead Suede Bomber J...,https://mercari.com/us/item/m37380984942/,48.61,2024-12-11,23
57,Vintage 1980 Boston Red Sox Burlap Wall Hangin...,https://mercari.com/us/item/m31262427088/,47.49,2024-12-11,23
58,Cariuma Oca Low Men Size 9 Green Canvas Skate ...,https://mercari.com/us/item/m37284374943/,47.49,2024-12-11,23
59,Videoke VMP-9000 Karaoke Music Player VCD Test...,https://mercari.com/us/item/m77939325225/,47.12,2024-12-11,23
60,Vintage RCA Color Video Camera CC004 Untested ...,https://mercari.com/us/item/m50823835379/,46.87,2024-12-11,23
61,VTG 1972 Aurora Skittle Pool Tabletop Billiard...,https://mercari.com/us/item/m55673026021/,46.57,2024-12-11,23
62,DJ Absolut The Heart Of New York Rap Cassette ...,https://mercari.com/us/item/m20941457122/,45.56,2024-12-11,23
63,Cutmaster C Cut Vs The World Cassette Mixtape ...,https://mercari.com/us/item/m12710073678/,45.56,2024-12-11,23
64,The Pack AD Long Sleeve Baseball Tee Size L Wh...,https://mercari.com/us/item/m86388253760/,45.12,2024-12-11,23
65,Authentic Nike New England Patriots NFL 100 Ye...,https://mercari.com/us/item/m81485306605/,45.00,2024-12-11,23
66,Lot of 32 Boston Red Sox Pendants 2005 Pendant...,https://mercari.com/us/item/m82715818136/,44.99,2024-12-05,29
67,Samsung PS-WK450 Subwoofer Only Tested Working...,https://mercari.com/us/item/m34494673350/,44.99,2024-12-19,15
68,Worcester Red Sox Woo Sox Smiley Ball Bobblehe...,https://mercari.com/us/item/m66489019504/,42.99,2024-12-12,22
69,Vintage Big Royal View 35mm Film Camera Tested...,https://mercari.com/us/item/m59490454857/,42.86,2024-12-11,23
70,"Element TWIGS Tosh Townend 7"" Complete Skatebo...",https://mercari.com/us/item/m51880778460/,42.84,2024-12-11,23
71,CapTel 2400iBT Ultratec Captioned Hearing Impa...,https://mercari.com/us/item/m71606274524/,41.66,2024-12-11,23
72,Vintage 90s Nike Reversible Jacket Size XL Fle...,https://mercari.com/us/item/m53224129124/,41.66,2024-12-11,23
73,Vintage LL Bean Mountain Guide Gore Tex Jacket...,https://mercari.com/us/item/m22114420124/,40.60,2024-12-11,23
74,Coldplay Rainbow Spellout Bucket Hat OSFA Blac...,https://mercari.com/us/item/m32138406958/,39.99,2024-12-17,17
75,Focusrite iTrack Studio Monitoring Headphones ...,https://mercari.com/us/item/m34091739658/,39.99,2024-12-13,21
76,Reebok Duffle Bag Purple Black Straps Nylon Vi...,https://mercari.com/us/item/m74146752560/,38.57,2024-12-11,23
77,VTG New England Patriots 2001 AFC Champions Ha...,https://mercari.com/us/item/m60849989025/,37.99,2024-12-11,23
78,Mitchell &amp; Ness Denver Nuggets Alex Englis...,https://mercari.com/us/item/m51897332237/,37.97,2024-12-11,23
79,MLB Boston Red Sox Full Zip Jacket Size 2XL Re...,https://mercari.com/us/item/m25181064069/,37.49,2024-12-11,23
80,CROM ILLUSTRATION OOF Coach Jacket Size M Butt...,https://mercari.com/us/item/m15744264697/,37.49,2024-12-11,23
81,Sylvan Esso Shaking Out The Numb Tour Long Sle...,https://mercari.com/us/item/m75215671240/,36.09,2024-12-11,23
82,Vintage Champion Authentic Vince Carter USA Ba...,https://mercari.com/us/item/m39036983322/,35.43,2024-12-11,23
83,All American Collection Georgetown Allen Ivers...,https://mercari.com/us/item/m26304687408/,35.43,2024-12-11,23
84,Minecraft Ender Dragon Mask Plastic Wearable L...,https://mercari.com/us/item/m66223852932/,34.99,2024-12-17,17
85,Vintage Compco Reflex 620 TLR Film Camera With...,https://mercari.com/us/item/m12199070929/,34.99,2024-12-27,7
86,Reebok ATR Chill Sneakers Mens Size 9.5 White ...,https://mercari.com/us/item/m69482000582/,34.99,2024-12-14,20
87,Vintage Bell System Western Electric Rotary Te...,https://mercari.com/us/item/m40044154512/,34.99,2024-12-27,7
88,Sony Dream Machine ICF-CS10ip Alarm Clock AM F...,https://mercari.com/us/item/m51032125701/,34.99,2024-12-14,20
89,Lowerclass Brats Just Like Clockwork T Shirt S...,https://mercari.com/us/item/m34618306727/,34.72,2024-12-11,23
90,DJ G Brown Like A Breath Of Fresh Air Promo CD...,https://mercari.com/us/item/m74969049943/,34.72,2024-12-11,23
91,Vintage 80s Fisher Price Nursery Monitor In Bo...,https://mercari.com/us/item/m77230510419/,34.72,2024-12-11,23
92,Callaway Opti Dri Golf Polo Shirt Size XL New ...,https://mercari.com/us/item/m89126274045/,34.72,2024-12-11,23
93,DJ Doggtime The Art Of Blending Promo Mixtape ...,https://mercari.com/us/item/m71802941774/,34.72,2024-12-11,23
94,Majestic Boston Red Sox Daisuke Matsuzaka Spri...,https://mercari.com/us/item/m18263233349/,34.72,2024-12-11,23
95,Vintage Columbia Sportswear Bugaboo Jacket Men...,https://mercari.com/us/item/m54991263692/,34.72,2024-12-11,23
96,General Electric AM FM Stereo Cassette Recorde...,https://mercari.com/us/item/m49989726123/,34.29,2024-12-11,23
97,The Craft VHS 1996 Fairuza Balk Robin Tunney N...,https://mercari.com/us/item/m27950372921/,33.99,2024-12-19,15
98,Golf Nintendo NES CIB Complete Tested Working ...,https://mercari.com/us/item/m32122473636/,33.74,2024-12-11,23
99,Vintage Snowboard Boots Size 9 Blue Gray Nubuc...,https://mercari.com/us/item/m41370365909/,33.74,2024-12-11,23
100,Fellowes CD Tower 75 Disc Capacity New Sealed NOS,https://mercari.com/us/item/m76602281173/,33.74,2024-12-11,23
101,VTG New Era Goo Goo Dolls 4th of July 2004 Buf...,https://mercari.com/us/item/m31040897605/,33.74,2024-12-11,23
102,Star Trek 25th Anniversary Nintendo Game Boy B...,https://mercari.com/us/item/m69025609636/,33.24,2024-12-11,23
103,Adidas New Zealand All Blacks Rugby Ball White...,https://mercari.com/us/item/m55205329848/,33.24,2024-12-11,23
104,VTG Tudor Mickey Mouse Electric Treasure Hunt ...,https://mercari.com/us/item/m43910192023/,32.59,2024-12-11,23
105,Vintage Riesen Chocolate Chew Duffle Bag Black...,https://mercari.com/us/item/m75915965453/,32.59,2024-12-11,23
106,Rugby World Cup 2011 Australia Jersey Size L W...,https://mercari.com/us/item/m65798390075/,32.57,2024-12-11,23
107,MLB St Louis Cardinals Lars Nootbaar Noot Nick...,https://mercari.com/us/item/m10639320640/,31.58,2024-12-11,23
108,Reebok Classics Question Mid Michigan State Sn...,https://mercari.com/us/item/m12029651542/,30.94,2024-12-11,23
109,Ride Snowboards Orion Snowboard Boots Size Wom...,https://mercari.com/us/item/m65793281406/,30.37,2024-12-11,23
110,Adidas Golden State Warriors Kevin Durant Shor...,https://mercari.com/us/item/m41268212199/,30.37,2024-12-11,23
111,USA Hockey Exclusive Collection Sleeveless Jer...,https://mercari.com/us/item/m42193555424/,30.37,2024-12-11,23
112,JuJuBe Paisley Floral Pattern Backpack Diaper ...,https://mercari.com/us/item/m96015505453/,30.27,2024-12-11,23
113,CASE ONLY For Sony Video8 Camcorder CCD-V5 CCD...,https://mercari.com/us/item/m23183292078/,30.00,2024-12-12,22
114,The North Face Heritage Patch Crewneck Sweatsh...,https://mercari.com/us/item/m47702788486/,29.99,2024-12-09,25
115,Puma Maccabi Tel Aviv 2010-11 Home Soccer Jers...,https://mercari.com/us/item/m47169585146/,29.99,2024-12-11,23
116,GPX Model A2935 Personal Cassette Player AM FM...,https://mercari.com/us/item/m52292923769/,29.99,2024-12-12,22
117,Boston Red Sox 2004 World Series Champs T Shir...,https://mercari.com/us/item/m71753031921/,29.99,2024-12-17,17
118,Nike Sportswear Love And Peace T Shirt Size 2X...,https://mercari.com/us/item/m21627822666/,29.99,2024-12-09,25
119,Vintage Sony ICF-34 AM FM TV Weather Radio Ful...,https://mercari.com/us/item/m46463278658/,29.99,2024-12-27,7
120,Marine Corps University Quang Tri Campus Sweat...,https://mercari.com/us/item/m66986312102/,29.99,2024-12-09,25
121,Uniqlo UT Archive Metal Gear Solid 2 T Shirt S...,https://mercari.com/us/item/m84557412657/,29.77,2024-12-11,23
122,VTG 90s Coca Cola Refreshing Races Hat Flag Em...,https://mercari.com/us/item/m75436103002/,28.49,2024-12-11,23
123,Nickelodeon Rugrats Lookie Cookies 3D Balancin...,https://mercari.com/us/item/m63412685961/,28.49,2024-12-11,23
124,Vintage 90s Washington Capitals Eastern Confer...,https://mercari.com/us/item/m47914494537/,28.12,2024-12-11,23
125,Vintage Champion Reverse Weave Pullover Sweats...,https://mercari.com/us/item/m36138337006/,28.12,2024-12-11,23
126,VTG 80s AT&amp;T Model 6500 Portable Electric ...,https://mercari.com/us/item/m97890638764/,28.12,2024-12-11,23
127,OEM Subaru Outback 2016 2017 2018 Floor Mats B...,https://mercari.com/us/item/m62224170135/,28.12,2024-12-11,23
128,Reeses Peanut Butter Cups Hoodie Size L Orange...,https://mercari.com/us/item/m40494143019/,27.99,2024-12-17,17
129,Champion Reverse Weave Hoodie Size L Script Lo...,https://mercari.com/us/item/m33478373687/,27.99,2024-12-09,25
130,VTG 90s New England Cape Cod Cranberry T Shirt...,https://mercari.com/us/item/m82303510293/,27.99,2024-12-17,17
131,Vintage Jerzees New England Patriots Football ...,https://mercari.com/us/item/m98369945712/,27.99,2024-12-17,17
132,Kawasaki AV1000 Home Theater System AV Switche...,https://mercari.com/us/item/m63097141058/,27.94,2024-12-11,23
133,VTG Tonka Tote Deluxe Racing Set Boxed Mostly ...,https://mercari.com/us/item/m84812679504/,27.94,2024-12-11,23
134,New England Patriots Zubaz Hoodie Size L New W...,https://mercari.com/us/item/m77161673734/,27.77,2024-12-11,23
135,Nike Venture Runner Sneakers Mens Size 13 Ratt...,https://mercari.com/us/item/m68764438306/,27.77,2024-12-11,23
136,Sean John Velour Track Jacket Size 2XLT Black ...,https://mercari.com/us/item/m14955323689/,27.77,2024-12-11,23
137,Nike Flight Retro Windbreaker Jogger Track Pan...,https://mercari.com/us/item/m19385695153/,27.77,2024-12-11,23
138,Jeep Travel Equipment Quarter Zip Sweatshirt S...,https://mercari.com/us/item/m69141132103/,27.77,2024-12-11,23
139,Vintage 80s East West Pullover Ski Jacket Size...,https://mercari.com/us/item/m36467222471/,27.77,2024-12-11,23
140,Reebok NFL Super Bowl XXXVIII 38 Adjustable Ha...,https://mercari.com/us/item/m83354917654/,27.77,2024-12-11,23
141,Vintage Champion Pullover Windbreaker Size L V...,https://mercari.com/us/item/m35653085469/,27.07,2024-12-11,23
142,Nicki Minaj PInk Friday 2 T Shirt Size L White...,https://mercari.com/us/item/m32236722443/,26.99,2024-12-17,17
143,Godsmack 2018 T Shirt Size XL Bostons Own Est ...,https://mercari.com/us/item/m62860318690/,26.99,2024-12-17,17
144,Links Crossbow Training Nintendo Wii Zapper an...,https://mercari.com/us/item/m64853534827/,26.60,2024-12-11,23
145,Vintage 2001 Old School Ball Park Baseball Gam...,https://mercari.com/us/item/m91771144096/,26.46,2024-12-11,23
146,Pair of 2 Sharp CP-C333 Speakers Left and Righ...,https://mercari.com/us/item/m33729572890/,25.72,2024-12-11,23
147,Vintage 90s Home Smart Home Hat Adjustable Str...,https://mercari.com/us/item/m85335324174/,25.57,2024-11-29,35
148,Zubaz Syracuse University Drawstring Pants Siz...,https://mercari.com/us/item/m96047309956/,25.31,2024-12-11,23
149,Adidas All Over Print Logo Hoodie Size M Black...,https://mercari.com/us/item/m67805869265/,25.26,2024-12-11,23
150,Retro Brand Pawtucket Red Sox PawSox Sweatshir...,https://mercari.com/us/item/m55707364569/,25.26,2024-12-11,23
151,Drake Vs Lil Wayne 2014 Tour Dates T Shirt Siz...,https://mercari.com/us/item/m42854259160/,25.26,2024-12-11,23
152,LL Bean Unisex Geometric Fleece Pullover Half ...,https://mercari.com/us/item/m31221440090/,25.26,2024-12-11,23
153,Adidas New England Revolution Soft Shell Bombe...,https://mercari.com/us/item/m19843529710/,25.26,2024-12-11,23
154,RCA Personal Portable Cassette Player Recorder...,https://mercari.com/us/item/m38045418483/,24.99,2024-12-21,13
155,Chassis Grip Block ONLY For Sony CCD-V5 V50 Se...,https://mercari.com/us/item/m85797597309/,24.99,2024-12-12,22
156,Adidas Boston Celtics Kevin Garnett Jersey Siz...,https://mercari.com/us/item/m14589038561/,24.99,2024-12-23,11
157,Charlie Daniels Band Red White And Blue Logo T...,https://mercari.com/us/item/m76350465928/,24.99,2024-12-27,7
158,CNN Plus Half Zip Collared Sweatshirt Size XL ...,https://mercari.com/us/item/m34481939757/,24.99,2024-12-09,25
159,Bravado Black Sabbath Vol 4 T Shirt Size XL Bl...,https://mercari.com/us/item/m64047913730/,24.99,2024-12-17,17
160,New England Patriots Super Bowl XXXIX Champs S...,https://mercari.com/us/item/m53451772207/,24.99,2024-12-11,23
161,Lot of 5 Minnesota Twins 1991 Season Plastic C...,https://mercari.com/us/item/m28522393636/,24.99,2024-12-13,21
162,Vintage 80s Adidas Nylon Windbreaker Pants Siz...,https://mercari.com/us/item/m64184345674/,24.99,2024-12-11,23
163,PING Collection Golf Sweater Mens Size XL Ligh...,https://mercari.com/us/item/m40527571023/,24.99,2024-12-16,18
164,New England Patriots Coors Light 36 Pack Coole...,https://mercari.com/us/item/m18387248083/,24.99,2024-12-21,13
165,Thrasher Magazine Flame Logo Hoodie Size M Nav...,https://mercari.com/us/item/m99367838950/,24.99,2024-12-09,25
166,The Clapper Star Wars Darth Vader Clap Activat...,https://mercari.com/us/item/m11714549409/,24.99,2024-12-13,21
167,RCA Personal Portable Cassette Player Recorder...,https://mercari.com/us/item/m11168613734/,24.99,2024-12-21,13
168,Vintage 90s Puma New England Patriots Hat Snap...,https://mercari.com/us/item/m41643859208/,24.29,2024-12-11,23
169,Vintage 90s Sports Specialties Florida Gators ...,https://mercari.com/us/item/m52257351350/,24.29,2024-12-11,23
170,Vintage 90s Sports Specialties Green Bay Packe...,https://mercari.com/us/item/m81595272244/,24.29,2024-12-11,23
171,Tough Duck Wool Hooded Workwear Jacket Size 3X...,https://mercari.com/us/item/m90993359183/,24.29,2024-12-11,23

Item 1 of 551 (Pair of 2 Technics SB-K25 Floor Speakers 3-Way System Tested Working No Scuffs)
 Old Price: 342.94 New Price: 325.79
Item 2 of 551 (Panasonic RF-2800 Shortwave AM FM Radio Tested Working w/ Power Cord and Antenna)
 Old Price: 299.99 New Price: 284.99
Item 3 of 551 (Yamaha R-N301 Stereo Receiver Fully Tested No Remote Net Connected 2 Channel)
 Old Price: 249.99 New Price: 237.49
Item 4 of 551 (Bose 321 GS Series II DVD Home Entertainment System Complete Fully Tested Works)
 Old Price: 199.99 New Price: 189.99
Item 5 of 551 (Vintage Claudia Grau Patchwork Blazer Jacket Size Petite 4 Bespoke 80s)
 Old Price: 180.49 New Price: 171.47
Item 6 of 551 (Set of 2 EPI T/E 70 Speakers Time Energy Series Fully Tested Working New Rings)
 Old Price: 171.0 New Price: 162.45
Item 7 of 551 (Vintage Zenith C585W Turntable AM FM Radio Tested Working Wood Grain New Stylus)
 Old Price: 169.99 New Price: 161.49
Item 8 of 551 (Life Like Racing NASCAR Electric Slot Car Championship Challenge 99% Complete)
 Old Price: 149.99 New Price: 142.49
Item 9 of 551 (Royal Retros Vintage Icons Washington Senators Satin Bomber Jacket Size 2XL)
 Old Price: 126.57 New Price: 120.24
Item 10 of 551 (Vintage Sawyers Mirascreen Slide Projector Viewer Tested Working Beige Plastic)
 Old Price: 99.99 New Price: 94.99
Item 11 of 551 (Vintage Bullock &amp; Jones Genuine Leather Bomber Jacket Size 44 XL Green Full Zip)
 Old Price: 89.99 New Price: 85.49
Item 12 of 551 (Nerf N Strike Stampede ECS Dart Blaster Tested Working Clear Green 18 Dart Clip)
 Old Price: 89.99 New Price: 85.49
Item 13 of 551 (VTG 90s Meshuggah Head Logo Zip Hoodie Size L Black Double Sided Spellout)
 Old Price: 89.99 New Price: 85.49
Item 14 of 551 (Tackla V Sport Factory Bulls Playstation Hockey Jersey Black Size XL)
 Old Price: 87.49 New Price: 83.12
Item 15 of 551 (Vintage 90s Champion Reverse Weave Sweatshirt Size XL Crewneck Blue Green)
 Old Price: 84.99 New Price: 80.74
Item 16 of 551 (Vintage 1985 Coca Cola Super Bowl XIX 19 Umbrella Wood Handle 52 Inch Diameter)
 Old Price: 84.87 New Price: 80.63
Item 17 of 551 (Vintage Sears Electric Power 12 Typewriter In Carry Case Tested Working Green)
 Old Price: 83.32 New Price: 79.15
Item 18 of 551 (Verit Industries Model 1030 Speakers Vintage Home Audio Tested Working 70s)
 Old Price: 81.0 New Price: 76.95
Item 19 of 551 (Sony CDP-C500 CD Player 5 Disc Carousel Changer Fully Tested Working No Remote)
 Old Price: 76.0 New Price: 72.2
Item 20 of 551 (Pioneer PD-M423 CD Player with New Optimus 6 Disc Cartidge Tested Working 1996)
 Old Price: 75.99 New Price: 72.19
Item 21 of 551 (Soundesign AM FM Stereo Receiver Double Cassette Recorder 5888 BLK Tested)
 Old Price: 71.24 New Price: 67.68
Item 22 of 551 (Polk Audio PSW120 Powered Subwoofer 90W Tested Working Repaired Leg)
 Old Price: 69.99 New Price: 66.49
Item 23 of 551 (Reebok Authentic Boston Bruins Milan Lucic Home Jersey Size XL Sewn)
 Old Price: 69.99 New Price: 66.49
Item 24 of 551 (Blind Skateboard Complete Checkerboard Graphic Tensor Trucks 7.5x31)
 Old Price: 64.99 New Price: 61.74
Item 25 of 551 (In Win BP655 Mini ITX PC Case w/ 200W Power Supply Tested Working Black)
 Old Price: 64.99 New Price: 61.74
Item 26 of 551 (MethSydnicate Shaniacidal Twaindencies T Shirt Size M Man I Feel Like A Pepsi)
 Old Price: 63.17 New Price: 60.01
Item 27 of 551 (Leisure Suit Larry Love For Sale PC Big Box ONLY No Game Incl Manual Reg Card)
 Old Price: 61.74 New Price: 58.65
Item 28 of 551 (Vintage Reebok Authentic Jason Kidd USA Basketball Jersey Size 2XL 52 Red)
 Old Price: 60.74 New Price: 57.7
Item 29 of 551 (Vintage 70s Battery Operated Large Sound Train Set Tested Working In Box PE 2011)
 Old Price: 59.99 New Price: 56.99
Item 30 of 551 (Adidas MLS LA Galaxy 2017 Away Jersey Size 2XL Herbalife Blue)
 Old Price: 59.99 New Price: 56.99
Item 31 of 551 (Mitchell &amp; Ness Arizona Diamondbacks Randy Johnson Jersey Size XL Cooperstown)
 Old Price: 59.99 New Price: 56.99
Item 32 of 551 (Sony ICF-CD873 AM FM CD Clock Radio Tested Working Mega Bass Voice Plus)
 Old Price: 59.99 New Price: 56.99
Item 33 of 551 (Sony CFD-S33 Portable Stereo Boombox AM FM CD Tape Fully Tested Belts Replaced)
 Old Price: 59.99 New Price: 56.99
Item 34 of 551 (PUMA X Mr Doodle All Over Print Half Zip Jacket Size L Black Blue 530648-01)
 Old Price: 59.99 New Price: 56.99
Item 35 of 551 (Sony CFD-S22 Portable Stereo Boombox AM FM CD Tape Fully Tested Working)
 Old Price: 59.99 New Price: 56.99
Item 36 of 551 (Nintendo Wii Skylanders Lot 3 Games 3 Portals 4 Figures Double Trouble Whirlwind)
 Old Price: 56.99 New Price: 54.14
Item 37 of 551 (Boston Red Sox 2024 Japanese Celebration SGA Jersey XL New Sealed Great Wave)
 Old Price: 55.55 New Price: 52.77
Item 38 of 551 (Bose SoundDock Digital Music System Speaker Tested iPod Input No Remote Series 1)
 Old Price: 54.99 New Price: 52.24
Item 39 of 551 (Hasbro Beyblade Burst Surge Speedstorm Slayer Showdown Battle Set w/ BeyStadium)
 Old Price: 54.99 New Price: 52.24
Item 40 of 551 (Canon EOS Rebel S SLR 35mm Film Camera Tested Working w/ Manual No Lens)
 Old Price: 52.24 New Price: 49.63
Item 41 of 551 (KNEX Rippin Rocket Roller Coaster Building Set Mostly Complete 2003 61366)
 Old Price: 52.08 New Price: 49.48
Item 42 of 551 (Band Hero Wireless Drum Kit Controller Nintendo Wii Pad Section Only 95521.808)
 Old Price: 52.08 New Price: 49.48
Item 43 of 551 (Arco Dupli Disk Hard Drive Duplicator IDE Ports Powers On Includes 2 Hard Drives)
 Old Price: 50.63 New Price: 48.1
Item 44 of 551 (Western Digital 13GB 7200RPM IDE Hard Drive 3.5 Inch 2MB Cache Tested)
 Old Price: 50.63 New Price: 48.1
Item 45 of 551 (VTG New England Patriots 2001 AFC Champs Framed Photo 13x16 Bar Decor)
 Old Price: 50.0 New Price: 47.5
Item 46 of 551 (Boston Red Sox Nation Pitchers Framed Photo 13x16 Bar Decor 2007 Season)
 Old Price: 50.0 New Price: 47.5
Item 47 of 551 (Jon Lester Red Sox No Hitter May 19 2008 Framed Photo 13x16 Bar Decor Fenway)
 Old Price: 50.0 New Price: 47.5
Item 48 of 551 (Long Live Virgil Abloh T Shirt Size L Blue White Cloud Bee Graphic)
 Old Price: 49.99 New Price: 47.49
Item 49 of 551 (Colosseum UConn Huskies Basketball Jersey Size 2XL Number 34 Ray Allen)
 Old Price: 49.99 New Price: 47.49
Item 50 of 551 (Earthgang 2022 Tour T Shirt Size L Double Sided Comfort Colors Tour Dates)
 Old Price: 49.99 New Price: 47.49
Item 51 of 551 (Vintage 90s Warner Bros Studio Store Rugby Shirt Size XL Black White Chest Logo)
 Old Price: 49.99 New Price: 47.49
Item 52 of 551 (RCA CC439 VHS Camcorder For Parts Tape Error Includes Case Battery Charger Cord)
 Old Price: 49.99 New Price: 47.49
Item 53 of 551 (Reebok On Field Baltimore Ravens Michael Oher Jersey Size 54 XL Blind Side Sewn)
 Old Price: 49.99 New Price: 47.49
Item 54 of 551 (Vintage Bentley 100A Deluxe Black And White Portable 5 Inch CRT TV In Box Tested)
 Old Price: 49.99 New Price: 47.49
Item 55 of 551 (DC Shoes Black Sabbath Slip On Sneakers Size Mens 9.5 Black Purple)
 Old Price: 48.61 New Price: 46.18
Item 56 of 551 (Vintage 90s The Territory Ahead Suede Bomber Jacket Size L Tan Button Front)
 Old Price: 48.61 New Price: 46.18
Item 57 of 551 (Vintage 90s The Territory Ahead Suede Bomber Jacket Size L Brown Button Front)
 Old Price: 48.61 New Price: 46.18
Item 58 of 551 (Vintage 1980 Boston Red Sox Burlap Wall Hanging Game Schedule Calendar 16x28)
 Old Price: 47.49 New Price: 45.12
Item 59 of 551 (Cariuma Oca Low Men Size 9 Green Canvas Skate Urban Sneakers Shoes 100103E01M)
 Old Price: 47.49 New Price: 45.12
Item 60 of 551 (Videoke VMP-9000 Karaoke Music Player VCD Tested Working No Remote or Microphone)
 Old Price: 47.12 New Price: 44.76
Item 61 of 551 (Vintage RCA Color Video Camera CC004 Untested No Damage Viewfinder Handle)
 Old Price: 46.87 New Price: 44.53
Item 62 of 551 (VTG 1972 Aurora Skittle Pool Tabletop Billiards Game 5511 Boxed Mostly Complete)
 Old Price: 46.57 New Price: 44.24
Item 63 of 551 (DJ Absolut The Heart Of New York Rap Cassette Mixtape Promo Tape Tested Hip Hop)
 Old Price: 45.56 New Price: 43.28
Item 64 of 551 (Cutmaster C Cut Vs The World Cassette Mixtape Rap Tape Promo Rare 1998 Hip Hop)
 Old Price: 45.56 New Price: 43.28
Item 65 of 551 (The Pack AD Long Sleeve Baseball Tee Size L White Black Wolf Shark Logo)
 Old Price: 45.12 New Price: 42.86
Item 66 of 551 (Authentic Nike New England Patriots NFL 100 Years Sideline All White Jacket 2XL)
 Old Price: 45.0 New Price: 42.75
Item 67 of 551 (Lot of 32 Boston Red Sox Pendants 2005 Pendant Collection 30 Sealed 2 Opened)
 Old Price: 44.99 New Price: 42.74
Item 68 of 551 (Samsung PS-WK450 Subwoofer Only Tested Working Black w/ Power Cord 14x12x7)
 Old Price: 44.99 New Price: 42.74
Item 69 of 551 (Worcester Red Sox Woo Sox Smiley Ball Bobblehead 2022 Season In Box)
 Old Price: 42.99 New Price: 40.84
Item 70 of 551 (Vintage Big Royal View 35mm Film Camera Tested In Bag With Flash Modules)
 Old Price: 42.86 New Price: 40.72
Item 71 of 551 (Element TWIGS Tosh Townend 7" Complete Skateboard Shadow Trucks 50mm Wheels)
 Old Price: 42.84 New Price: 40.7
Item 72 of 551 (CapTel 2400iBT Ultratec Captioned Hearing Impaired Touch Screen Telephone Tested)
 Old Price: 41.66 New Price: 39.58
Item 73 of 551 (Vintage 90s Nike Reversible Jacket Size XL Fleece Lined Windbreaker Green Black)
 Old Price: 41.66 New Price: 39.58
Item 74 of 551 (Vintage LL Bean Mountain Guide Gore Tex Jacket Size XL Blue Black)
 Old Price: 40.6 New Price: 38.57
Item 75 of 551 (Coldplay Rainbow Spellout Bucket Hat OSFA Black Multicolor)
 Old Price: 39.99 New Price: 37.99
Item 76 of 551 (Focusrite iTrack Studio Monitoring Headphones HP60S Tested Working Silver)
 Old Price: 39.99 New Price: 37.99
Item 77 of 551 (Reebok Duffle Bag Purple Black Straps Nylon Vintage 90s 30x13x12)
 Old Price: 38.57 New Price: 36.64
Item 78 of 551 (VTG New England Patriots 2001 AFC Champions Hat Adjustable NWT Blue Deadstock)
 Old Price: 37.99 New Price: 36.09
Item 79 of 551 (Mitchell &amp; Ness Denver Nuggets Alex English Jersey Size 56 3XL Rainbow Logo)
 Old Price: 37.97 New Price: 36.07
Item 80 of 551 (MLB Boston Red Sox Full Zip Jacket Size 2XL Red Spellout G III Carl Banks)
 Old Price: 37.49 New Price: 35.62
Item 81 of 551 (CROM ILLUSTRATION OOF Coach Jacket Size M Button Front Skull Black)
 Old Price: 37.49 New Price: 35.62
Item 82 of 551 (Sylvan Esso Shaking Out The Numb Tour Long Sleeve T Shirt Size L 2021)
 Old Price: 36.09 New Price: 34.29
Item 83 of 551 (Vintage Champion Authentic Vince Carter USA Basketball Jersey Size 2XL 52)
 Old Price: 35.43 New Price: 33.66
Item 84 of 551 (All American Collection Georgetown Allen Iverson Basketball Jersey Size 56 2XL)
 Old Price: 35.43 New Price: 33.66
Item 85 of 551 (Minecraft Ender Dragon Mask Plastic Wearable Light Up Tested Working Black)
 Old Price: 34.99 New Price: 33.24
Item 86 of 551 (Vintage Compco Reflex 620 TLR Film Camera With Reflex Flash Unit And Manuals)
 Old Price: 34.99 New Price: 33.24
Item 87 of 551 (Reebok ATR Chill Sneakers Mens Size 9.5 White Low Top Cleaned)
 Old Price: 34.99 New Price: 33.24
Item 88 of 551 (Vintage Bell System Western Electric Rotary Telephone Black Untested CD 500)
 Old Price: 34.99 New Price: 33.24
Item 89 of 551 (Sony Dream Machine ICF-CS10ip Alarm Clock AM FM Radio iPod Dock Tested No Remote)
 Old Price: 34.99 New Price: 33.24
Item 90 of 551 (Lowerclass Brats Just Like Clockwork T Shirt Size L Punk Rock)
 Old Price: 34.72 New Price: 32.98
Item 91 of 551 (DJ G Brown Like A Breath Of Fresh Air Promo CD Tested MOP Eminem Fat Joe 2000)
 Old Price: 34.72 New Price: 32.98
Item 92 of 551 (Vintage 80s Fisher Price Nursery Monitor In Box Fully Tested Working Beige 157)
 Old Price: 34.72 New Price: 32.98
Item 93 of 551 (Callaway Opti Dri Golf Polo Shirt Size XL New NWT Bright White)
 Old Price: 34.72 New Price: 32.98
Item 94 of 551 (DJ Doggtime The Art Of Blending Promo Mixtape CD Rap 2001 Instrumentals)
 Old Price: 34.72 New Price: 32.98
Item 95 of 551 (Majestic Boston Red Sox Daisuke Matsuzaka Spring Training Jersey Size 3XL)
 Old Price: 34.72 New Price: 32.98
Item 96 of 551 (Vintage Columbia Sportswear Bugaboo Jacket Mens Size XL Red Shell Green Liner)
 Old Price: 34.72 New Price: 32.98
Item 97 of 551 (General Electric AM FM Stereo Cassette Recorder 3-5454B Tested Belts Replaced)
 Old Price: 34.29 New Price: 32.58
Item 98 of 551 (The Craft VHS 1996 Fairuza Balk Robin Tunney Neve Campbell New Factory Sealed)
 Old Price: 33.99 New Price: 32.29
Item 99 of 551 (Golf Nintendo NES CIB Complete Tested Working 1985 Authentic)
 Old Price: 33.74 New Price: 32.05
Item 100 of 551 (Vintage Snowboard Boots Size 9 Blue Gray Nubuck 90s nice Brand)
 Old Price: 33.74 New Price: 32.05
Item 101 of 551 (Fellowes CD Tower 75 Disc Capacity New Sealed NOS)
 Old Price: 33.74 New Price: 32.05
Item 102 of 551 (VTG New Era Goo Goo Dolls 4th of July 2004 Buffalo Concert Hat Adjustable Rare)
 Old Price: 33.74 New Price: 32.05
Item 103 of 551 (Star Trek 25th Anniversary Nintendo Game Boy Box and Inserts Only No Game/Manual)
 Old Price: 33.24 New Price: 31.58
Item 104 of 551 (Adidas New Zealand All Blacks Rugby Ball White Black Purple Regulation Size 5)
 Old Price: 33.24 New Price: 31.58
Item 105 of 551 (VTG Tudor Mickey Mouse Electric Treasure Hunt Game Near Complete Missing Boat)
 Old Price: 32.59 New Price: 30.96
Item 106 of 551 (Vintage Riesen Chocolate Chew Duffle Bag Black Embroidered Logo Rare 28x12x12)
 Old Price: 32.59 New Price: 30.96
Item 107 of 551 (Rugby World Cup 2011 Australia Jersey Size L Wallabies Canterbury Long Sleeve)
 Old Price: 32.57 New Price: 30.94
Item 108 of 551 (MLB St Louis Cardinals Lars Nootbaar Noot Nickname Jersey Size XL SGA)
 Old Price: 31.58 New Price: 30.0
Item 109 of 551 (Reebok Classics Question Mid Michigan State Sneakers Size 8 2023 Green Toe)
 Old Price: 30.94 New Price: 29.39
Item 110 of 551 (Ride Snowboards Orion Snowboard Boots Size Womens 7 24cm Gray Blue)
 Old Price: 30.37 New Price: 28.85
Item 111 of 551 (Adidas Golden State Warriors Kevin Durant Short Sleeve Jersey Shirsey Size L)
 Old Price: 30.37 New Price: 28.85
Item 112 of 551 (USA Hockey Exclusive Collection Sleeveless Jersey Size 3XL Blue Shield Logo)
 Old Price: 30.37 New Price: 28.85
Item 113 of 551 (JuJuBe Paisley Floral Pattern Backpack Diaper Bag Black Multi)
 Old Price: 30.27 New Price: 28.76
Item 114 of 551 (CASE ONLY For Sony Video8 Camcorder CCD-V5 CCD-V50 Gray Plastic 16x11x5)
 Old Price: 30.0 New Price: 28.5
Item 115 of 551 (The North Face Heritage Patch Crewneck Sweatshirt Size Mens M Gray)
 Old Price: 29.99 New Price: 28.49
Item 116 of 551 (Puma Maccabi Tel Aviv 2010-11 Home Soccer Jersey Size Youth XXL Fits Adult S)
 Old Price: 29.99 New Price: 28.49
Item 117 of 551 (GPX Model A2935 Personal Cassette Player AM FM Radio New Sealed NOS Headphones)
 Old Price: 29.99 New Price: 28.49
Item 118 of 551 (Boston Red Sox 2004 World Series Champs T Shirt Sz L Now I Can Die In Peace NWT)
 Old Price: 29.99 New Price: 28.49
Item 119 of 551 (Nike Sportswear Love And Peace T Shirt Size 2XL Double Sided DQ1078-394)
 Old Price: 29.99 New Price: 28.49
Item 120 of 551 (Vintage Sony ICF-34 AM FM TV Weather Radio Fully Tested Clean Shape)
 Old Price: 29.99 New Price: 28.49
Item 121 of 551 (Marine Corps University Quang Tri Campus Sweatshirt Size XL Gray Red Black)
 Old Price: 29.99 New Price: 28.49
Item 122 of 551 (Uniqlo UT Archive Metal Gear Solid 2 T Shirt Size XL Blue Solid Snake)
 Old Price: 29.77 New Price: 28.28
Item 123 of 551 (VTG 90s Coca Cola Refreshing Races Hat Flag Embroidery Adjustable Gray Red)
 Old Price: 28.49 New Price: 27.07
Item 124 of 551 (Nickelodeon Rugrats Lookie Cookies 3D Balancing Game Near Complete Playable 90s)
 Old Price: 28.49 New Price: 27.07
Item 125 of 551 (Vintage 90s Washington Capitals Eastern Conference Champions Sign 1998 Bud Ice)
 Old Price: 28.12 New Price: 26.71
Item 126 of 551 (Vintage Champion Reverse Weave Pullover Sweatshirt Size XL Script Logo Gray)
 Old Price: 28.12 New Price: 26.71
Item 127 of 551 (VTG 80s AT&amp;T Model 6500 Portable Electric Typewriter For Parts Beeps When Typing)
 Old Price: 28.12 New Price: 26.71
Item 128 of 551 (OEM Subaru Outback 2016 2017 2018 Floor Mats Black Full Set Carpet J501SAL002)
 Old Price: 28.12 New Price: 26.71
Item 129 of 551 (Reeses Peanut Butter Cups Hoodie Size L Orange Embroidered Logo Pullover)
 Old Price: 27.99 New Price: 26.59
Item 130 of 551 (Champion Reverse Weave Hoodie Size L Script Logo Baby Blue Pullover)
 Old Price: 27.99 New Price: 26.59
Item 131 of 551 (VTG 90s New England Cape Cod Cranberry T Shirt Size XL Heather Gray NWT)
 Old Price: 27.99 New Price: 26.59
Item 132 of 551 (Vintage Jerzees New England Patriots Football Sweatshirt Size L Flying Elvis)
 Old Price: 27.99 New Price: 26.59
Item 133 of 551 (Kawasaki AV1000 Home Theater System AV Switcher Volume Control Tested Working)
 Old Price: 27.94 New Price: 26.54
Item 134 of 551 (VTG Tonka Tote Deluxe Racing Set Boxed Mostly Complete Missing Cars and 1 Handle)
 Old Price: 27.94 New Price: 26.54
Item 135 of 551 (New England Patriots Zubaz Hoodie Size L New With Tags NWT NFL Team Apparel)
 Old Price: 27.77 New Price: 26.38
Item 136 of 551 (Nike Venture Runner Sneakers Mens Size 13 Rattan Orange CK2944-202)
 Old Price: 27.77 New Price: 26.38
Item 137 of 551 (Sean John Velour Track Jacket Size 2XLT Black Soft Full Zip Y2K Vintage)
 Old Price: 27.77 New Price: 26.38
Item 138 of 551 (Nike Flight Retro Windbreaker Jogger Track Pants Size L CN8512 010)
 Old Price: 27.77 New Price: 26.38
Item 139 of 551 (Jeep Travel Equipment Quarter Zip Sweatshirt Size M Pullover Pale Yellow)
 Old Price: 27.77 New Price: 26.38
Item 140 of 551 (Vintage 80s East West Pullover Ski Jacket Size M Red Black Blue Anorak)
 Old Price: 27.77 New Price: 26.38
Item 141 of 551 (Reebok NFL Super Bowl XXXVIII 38 Adjustable Hat NWT Shark Tooth Patriots)
 Old Price: 27.77 New Price: 26.38
Item 142 of 551 (Vintage Champion Pullover Windbreaker Size L V Neck Striped Cuffs Collar Blue)
 Old Price: 27.07 New Price: 25.72
Item 143 of 551 (Nicki Minaj PInk Friday 2 T Shirt Size L White Double Sided)
 Old Price: 26.99 New Price: 25.64
Item 144 of 551 (Godsmack 2018 T Shirt Size XL Bostons Own Est 1995 Gray Double Sided)
 Old Price: 26.99 New Price: 25.64
Item 145 of 551 (Links Crossbow Training Nintendo Wii Zapper and Box Only NO GAME)
 Old Price: 26.6 New Price: 25.27
Item 146 of 551 (Vintage 2001 Old School Ball Park Baseball Game In Box Missing Balls and Flags)
 Old Price: 26.46 New Price: 25.14
Item 147 of 551 (Pair of 2 Sharp CP-C333 Speakers Left and Right Bookshelf Tested Working)
 Old Price: 25.72 New Price: 24.43
Item 148 of 551 (Vintage 90s Home Smart Home Hat Adjustable Strapback Retro Tech)
 Old Price: 25.57 New Price: 24.29
Item 149 of 551 (Zubaz Syracuse University Drawstring Pants Size XL NWT Zebra)
 Old Price: 25.31 New Price: 24.04
Item 150 of 551 (Adidas All Over Print Logo Hoodie Size M Black White GP4034)
 Old Price: 25.26 New Price: 24.0
Item 151 of 551 (Retro Brand Pawtucket Red Sox PawSox Sweatshirt Size XL Bear Claws)
 Old Price: 25.26 New Price: 24.0
Item 152 of 551 (Drake Vs Lil Wayne 2014 Tour Dates T Shirt Size XL Capcom Street Fighter)
 Old Price: 25.26 New Price: 24.0
Item 153 of 551 (LL Bean Unisex Geometric Fleece Pullover Half Snap Womens L Mens M)
 Old Price: 25.26 New Price: 24.0
Item 154 of 551 (Adidas New England Revolution Soft Shell Bomber Jacket Size XL Minor Flaw)
 Old Price: 25.26 New Price: 24.0
Item 155 of 551 (RCA Personal Portable Cassette Player Recorder RP3504-A Tested Battery Operated)
 Old Price: 24.99 New Price: 23.74
Item 156 of 551 (Chassis Grip Block ONLY For Sony CCD-V5 V50 Series Camcorders Tested Working)
 Old Price: 24.99 New Price: 23.74
Item 157 of 551 (Adidas Boston Celtics Kevin Garnett Jersey Size S Green Alternate Worn Print)
 Old Price: 24.99 New Price: 23.74
Item 158 of 551 (Charlie Daniels Band Red White And Blue Logo T Shirt Size XL God Military)
 Old Price: 24.99 New Price: 23.74

WebDriverException: Message: target frame detached: received Inspector.detached event
  (Session info: chrome=131.0.6778.205)
Stacktrace:
	GetHandleVerifier [0x0064EC13+23731]
	(No symbol) [0x005DC394]
	(No symbol) [0x004BBE63]
	(No symbol) [0x004AE9B8]
	(No symbol) [0x004ADBC7]
	(No symbol) [0x004AD527]
	(No symbol) [0x004AD441]
	(No symbol) [0x004AB8DB]
	(No symbol) [0x004ABF4D]
	(No symbol) [0x004B81EA]
	(No symbol) [0x004C78A5]
	(No symbol) [0x004CC6F6]
	(No symbol) [0x004AC555]
	(No symbol) [0x004C74D1]
	(No symbol) [0x0053B7A1]
	(No symbol) [0x00521BF6]
	(No symbol) [0x004F3F35]
	(No symbol) [0x004F4EBD]
	GetHandleVerifier [0x0092F0D3+3039603]
	GetHandleVerifier [0x00942DEA+3120778]
	GetHandleVerifier [0x0093B592+3089970]
	GetHandleVerifier [0x006E43B0+635984]
	(No symbol) [0x005E4DCD]
	(No symbol) [0x005E2068]
	(No symbol) [0x005E2205]
	(No symbol) [0x005D4FD0]
	BaseThreadInitThunk [0x7645FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77D9809E+286]
	RtlGetAppContainerNamedObjectPath [0x77D9806E+238]

In [ ]:
pricedrop_df

# Automate Sending Offers (XPATHs Here Likely Need To Be Updated)

In [70]:
driver = start_driver()

In [69]:
mercari_login(driver, 'username', 'password')

In [53]:
# go to active listings, sorted by number of likes
driver.get('https://www.mercari.com/mypage/listings/active/?sortBy=3')

In [54]:
page_source = driver.page_source
soup = BeautifulSoup(page_source, 'lxml')

In [83]:
def send_offers(driver, discount_pct, floor_price):
    global BeautifulSoup
    
    # go to active listings, sorted by number of likes
    driver.get('https://www.mercari.com/mypage/listings/active/?sortBy=3')

    page_source = driver.page_source
    soup = BeautifulSoup(page_source, 'lxml')

    # get list of products on page
    from bs4 import BeautifulSoup
    import re

    # empty vectors for variable storage
    links = []
    product_names = []
    prices = []
    dates = []

    for i in range(0, 1000):
        try:
            if i==1:
                driver.get('https://www.mercari.com/mypage/listings/active/?sortBy=3')
                WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[4]/main/div/div[3]/div[2]/ul/li[1]/div/div[3]/div/div[1]/a')))
            if i>1:
                driver.get('https://www.mercari.com/mypage/listings/active/?sortBy=3&page='+str(i))
                WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[4]/main/div/div[3]/div[2]/ul/li[1]/div/div[3]/div/div[1]/a')))
        except:
            pass

        # update page source
        page_source = driver.page_source
        soup = BeautifulSoup(page_source, 'lxml')

        # if "No results" is present on the page and no products are found, break loop
        if 'No items for sale' in soup.text and len(soup.find_all(attrs={"class":"Link-sc-us5oxt MenuLink-sc-1k5i400 koA-DLz ehDaPW T2-sc-1pugix3 MetaColumn__T2NoWrapEllipsis-sc-18c8425f-1 dNZGZp bhVasx"}, href=True)) == 0:
            print('No more items, done.')
            break

        else:
            # get item names, prices, offer button elements, number of likers
            itemnames = [x.text for x in driver.find_elements(By.XPATH, '//*[@data-testid="ItemLink"]')]
            prices = [float(x['value']) for x in soup.find_all("input", attrs={"name":"price"})]
            num_likers = [int(tag.text) for tag in driver.find_elements(By.XPATH, '//*[@class="T2-sc-1um8956 daMJEj"]')[1::2]]

            for i in range(len(itemnames)):
                itemname = itemnames[i]
                itemlikes = num_likers[i]
                itemprice = prices[i]

                if itemlikes > 0:
                    time.sleep(1)
                    offer_button = WebDriverWait(driver, 10).until(EC.presence_of_all_elements_located((By.XPATH, '//*[@data-testid="OfferButton"]')))[i]
                    driver.execute_script("arguments[0].scrollIntoView(true);", offer_button)
                    driver.execute_script("window.scrollBy(0, -400);")
                    rev_discount = 1 - (0.01 * discount_pct)
                    reduced_price = int(math.floor(rev_discount * itemprice))
                    if itemprice <= floor_price:
                        print(itemname, 'is below the provided floor price. No offer sent.')
                        pass
                    else:
                        offer_button.click()

                        # get suggested reduced price for invalid offer cases
                        time.sleep(1)
                        suggested_discountprice = float(WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="OfferToLikerInput"]'))).get_attribute('value'))
                        time.sleep(0.5)
                        if reduced_price > suggested_discountprice:
                            price_element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@name="offerPrice"]')))
                            price_element.click()
                            price_element.send_keys(Keys.RETURN);
                        else: 
                            price_element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@name="offerPrice"]')))
                            price_element.click()
                            price_element.send_keys(Keys.CONTROL + "a");
                            price_element.send_keys(Keys.DELETE);
                            price_element.send_keys(str(reduced_price))
                            price_element.send_keys(Keys.RETURN);
                        time.sleep(2)

                        # if an offer has already been sent, don't send
                        try:
                            # if there is an error when offering to a liker
                            if driver.find_element(By.XPATH, '//*[@data-testid="OfferToLikerError"]'):
                                # cases where an offer needs to be lower
                                if 'needs' in driver.find_element(By.XPATH, '//*[@data-testid="OfferToLikerError"]').text:
                                    highest_possible_offerprice = float(re.split('\$', driver.find_element(By.XPATH, '//*[@data-testid="OfferToLikerError"]').text)[-1])
                                    price_element = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@name="offerPrice"]')))
                                    price_element.click()
                                    price_element.send_keys(Keys.CONTROL + "a")
                                    price_element.send_keys(Keys.DELETE)
                                    price_element.send_keys(str(highest_possible_offerprice))
                                    price_element.send_keys(Keys.RETURN)
                                    sendoffer_button = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="MakeAnOfferButton"]')))
                                    sendoffer_button.click()
                                    print('Offer sent for', itemname + '.')
                                    time.sleep(2)
                                    driver.refresh()
                                    time.sleep(2.5)
                                # cases where an offer has already been sent
                                else:
                                    ActionChains(driver).send_keys(Keys.ESCAPE).perform()
                                    print('Offer has already been sent for', itemname + ' within the past 24 hours.')
                        # otherwise, send offer
                        except:
                            sendoffer_button = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@data-testid="MakeAnOfferButton"]')))
                            sendoffer_button.click()
                            print('Offer sent for', itemname + '.')
                            time.sleep(2.5)
                            driver.refresh()
                            time.sleep(2.5)
                else:
                    print('No items with likers on this page.')
                    break

In [84]:
# change i to start at page 5, try again. last error resulted from what mercari says is an item with no likes but it does have likes

In [85]:
send_offers(driver, 15, 10)

Adult Swim Metalocalypse Season 2 DVD Set Two Discs Tested Working is below the provided floor price. No offer sent.
Spongebob Squarepants Laugh Your Pants Off VHS Tested Working 5 Episodes 2003 is below the provided floor price. No offer sent.
Offer sent for Verit Industries Model 1030 Speakers Vintage Home Audio Tested Working 70s.
Offer sent for Element Skateboards All Terrain Urethane Skateboard Wheels 50mm Black Light Blue.
Offer sent for VTG Sony STR-VX1 Stereo Receiver AM FM Phono Tape Inputs Fully Tested Working.
Offer sent for Disney Toy Story Pizza Planet Sweatshirt Size L Black Red Tie Dye.
Offer sent for Fox Racing Flex Fit Baseball Hat Size L/XL Black Green White.
Offer sent for Sony Playstation 2 PS2 Dualshock Controller Clear Smoke Gray SCPH-10010 Tested.
Offer sent for Vintage The Mountain Wolf Shirt Mens Sz XL Tie Dye SS Native American Art Tee.
Offer sent for VTG 90s Pokemon Gotta Catch Em All Charmander Card Binder Holds 136 Cards Empty.
Offer sent for Shimano Ultegra Mesh Back Trucker Hat Adjustable Green Black Cycling.
Vintage Champion T Shirt Size S Blue Tag It Takes A Little More To Make is below the provided floor price. No offer sent.
Offer sent for . Dot Hack Legend Of The Twilight Bandai Manga Anime Music Soundtrack (CD, 2003).
NYKO Charge Station Nintendo Wii Remote Charging Dock ONLY Tested Working is below the provided floor price. No offer sent.
Offer sent for MV Sport Arkansas Razorbacks Crewneck Sweatshirt Size 2XL Gray.
Offer sent for Vintage 1998 Parker Brothers Quija Board Game Complete In Box 0404.
Offer sent for Lot of 114 Yu Gi Oh Cards Used Played Exodia Some Holos Monster Spell Trap Magic.
DreamGear My Arcade Gamer V Portable Hand Held System 220 Games in 1 Tested is below the provided floor price. No offer sent.
Offer sent for Beetlejuice Movie T Shirt Size XL Black Neon Graphic.
Offer sent for Vintage Disney Catalog Goofy Golf Hat Cap Tan Strapback 90s.
Offer sent for VTG 90s Gear For Sports Ogunquit Maine Crewneck Sweatshirt Size XL White Purple.
Offer sent for 47 Brand Boston Red Sox Strapback Baseball Hat Navy Blue White B Logo.
Offer sent for Peppa Pig Bucket Hat All Over Graphic Print Crown OSFA.
Offer sent for Y2K Boston Celtics NBA Elevation Hat Cap Green Gold Black Adjustable.
Vintage Champion Logo T Shirt Blue Bar Size M Black Red is below the provided floor price. No offer sent.
Bridgestone Firestone Hat Hot Graphic Black Automotive is below the provided floor price. No offer sent.
Offer sent for HUF Boom Triple Triangle Pullover Hoodie Size L Comic Art.
Offer sent for WWE Authentic Cody Rhodes American Nightmare T Shirt Size 2XL XXL.
Duran Duran Decade Greatest Hits VHS Tape Tested Working Capitol Video is below the provided floor price. No offer sent.
Offer sent for Wiz Khalifa Taylor Gang Hoodie Size Adult M Black Bar Logo.
Mischief Street Racing DVD 2002 Teckademics Tested Working is below the provided floor price. No offer sent.
Offer sent for Lot of 23 DVDs No Cases Futurama UFC Comedy Horror Movies.
Offer sent for Adidas Originals 3 Stripe Womens Cropped T Shirt Size L Black White.
Offer sent for Scream Ghost Face Let's Watch Scary Movies T Shirt Size XL Black.
Offer sent for Vintage Masters Art Wall Phone AM Radio Model RT-200 1965 Tested Powers On.
Offer sent for Vintage 90s Boston Celtics Kamball Door Hanging Basketball Hoop 24x16.
47 Brand Cleveland Browns Clean Up Strapback Hat Adjustable is below the provided floor price. No offer sent.
Offer sent for Playboy Bunny By Pacsun Red Logo Crewneck Embroidered T Shirt Mens L.
Offer sent for The North Face Berkeley California Snapback Hat Green Adjustable.
Offer sent for Sony CFD-S200 Portable CD Radio Cassette Player Stereo Boombox Tested Tape Buzz.
Offer sent for Vintage Mink Hand Muff Warmer Brown Fur Satin Lined Inner Zipper Pocket.
Offer sent for Boss Dog Art Dept Life's A Trip Death's A Journey T Shirt Size L Black.
Offer sent for Lot of 50 Plus Vintage Keychains Pins Buttons 80s 90s Auto Food Drink MA.
Offer sent for Vintage Sears Silvertone Instant Sound AM Clock Radio Flawed READ DESC.
Offer sent for Le Coq Sportif 2006-07 Sheffield United Away Jersey Size 46/48 XL.
Vintage 90s Jeff Gordon Hendrick Motorsports NASCAR Hat Adjustable Navy Blue is below the provided floor price. No offer sent.
Offer sent for Guitar Hero World Tour Xbox 360 Kramer Guitar Faceplate Only Replacement.
Offer sent for Fisher Audio Component System MC-712 Tested Partially Working READ DESC.
Maxim Magazine October 2008 Issue 130 Megan Fox Cover Transformers is below the provided floor price. No offer sent.
Offer sent for Vintage Champion Reverse Weave Hoodie Size Adult S Cut Collar Black.
Disneys DuckTales Season 1 DVD 3 Disc Box Set Tested Working Complete is below the provided floor price. No offer sent.
Offer sent for SOJA Reggae Band T Shirt Size S American Apparel 2009 Y2K.
Offer sent for Large Vintage Fashion Girl Jeep Toy Car Processed Plastics 70s Pink Blue Barbie.
Vintage Minolta Autopak 600-X Film Camera For Parts As Is Stuck Lever & Aperture is below the provided floor price. No offer sent.
Offer sent for Dave Matthews Band Circle Logo T Shirt Size L Green Blue.
Rugrats A Rugrats Vacation VHS Orange Tape 1997 Tested Working is below the provided floor price. No offer sent.
Offer sent for Vintage Y2K Mountain Dew Full Zip Windbreaker Jacket Size L Black White Logos.
Offer sent for VTG World Class Inc Geometric Pattern Collared Chunky Knit Wool Sweater Size L.
Offer sent for NERF N-Strike Elite Demolisher 2 in 1 Blaster Tested Working No Missile.
Offer sent for Blues Clues Board Game 1998 University Games Mostly Complete Missing Notebook.
Offer sent for Vintage Y2K Universal Studios 2005 T Shirt Size 3XL Gray.
Offer sent for HP Lifestyle Wired USB Keyboard TPC-001K Black Green Fully Tested Cheddar Slim.
Offer sent for Maxim Magazine February 2009 Issue 134 The Real Swimsuit Issue.
Offer sent for Rockport Pullover Jacket Purple Size XL Half Zip Vented Polyester.
Offer sent for Vintage Winston Cigarettes Trucker Hat Mesh Back Red Adjustable 80s.
Offer sent for Hard Turn Nipsey Hussle The Marathon Continues T Shirt Size L Printed Signature.
Maxim Magazine October 2007 Issue 118 Erica Durance Smallville Cover is below the provided floor price. No offer sent.
It's Christmas Time by Elvis Presley Audio CD 2000 Tested Working BMG is below the provided floor price. No offer sent.
Offer sent for VTG Gildan You Name It I'm Allergic To It Sweatshirt Size L Allergies.
Offer sent for Vintage Y2K Champion Crewneck Sweatshirt Size XL Gray Pullover Chest Logo.
Offer sent for Embroidered The Neon Coconut T Shirt Size L Black Pink Yellow Retro.
Offer sent for Camel Crown Mens Hook and Loop Sandals Waterproof Size 8 Blue Patterned.
Offer sent for Pair of Two Sony SS-U131 Home Theater Speakers Black Tested Working 200 W 8 Ohm.
Offer sent for TD by Priority Male Short Sleeve Button Front Dragon Shirt Size XL Orange Black.
Offer sent for Antique 1924 Singer Sewing Machine Model 99 Electric Tested Working.
Offer sent for Globe G2 Typhoon Complete Skateboard 7.75" Tensor Trucks 53mm Wheels.
Offer sent for Dell Vostro 200 PC 1TB HDD 2GB RAM Intel Pentium Dual Windows XP Home SP3 Retro.
Offer sent for New Era Titleist Boston Red Sox Baseball Hat Cap Adjustable B Logo Blue.
Offer sent for The Lion King Simbas Pride Hop A Croc Swamp Board Game Mattel Complete 1998.
Offer sent for Blizzard Overwatch Heroes T Shirt Size L Original Cast Gray Designed by Jinx.
Offer sent for Levi's 550 Jeans Mens Size 34x32 Light Wash Missing Hip Tag.
Offer sent for Vintage 90s Key West Florida Shark T Shirt Size XL Big Graphic.
Offer sent for Vintage 1998 RoseArt Finger Fashion Board Game Complete In Box.
Offer sent for Vintage Mickey Mouse Minnie Donald Spinning Light Up Roly Poly Toy Tested 90s.
Offer sent for TinyBuild Games Hat Tiny Build Orange Black Adjustable Hello Neighbor Publisher.
Offer sent for Cozumel Mexico Muscle Graphic Tank Top Shirt Size XL Beachwear.
Scholastic I Spy A Mumble Monster Mystery VHS Tape New Sealed HBO Family TV Show is below the provided floor price. No offer sent.
Offer sent for Punk In Drublic Craft Beer Music Festival Shirt Size L NOFX Bosstones Worcester.

Offer sent for Atomic Betaflex Ski Boots Size Mens 9.5 Womens 10.5 316mm Black.
Offer sent for Lot of 16 White Dwarf Magazines 2007 2018 2019 Games Workshop Warhammer 40K.
Offer sent for Lenovo ThinkCentre TIO24D 24" Tiny-In-One Widescreen LED IPS Monitor Tested.
Offer sent for Barbie Golfer T Shirt Size L Golf Pink Unisex Graphic Tee.
Offer sent for The Twilight Zone 2 Walking Distance Audio Book Cassette Rod Serling.
Offer sent for VTG New Era 2003 World Series 100th Anniversary Hat Yankees Marlins Reshaped.
Offer sent for Encore Tape 2 USB Cassette Converter Model 2034 Tested Working.
Angels And Airwaves We Dont Need To Whisper CD 2006 Tested Working is below the provided floor price. No offer sent.
Vintage New Era MLB All Star Fanfest Boston 1999 Snapback Hat Cleaned Reshaped is below the provided floor price. No offer sent.
Offer sent for VTG Smith Corona Electra CT Portable Electric Typewriter With Case Tested Blue.
Offer sent for Vintage EZ's By Haggar Full Zip Windbreaker Jacket Size L NWT Color Block.
Offer sent for Vintage Y2K AND1 Basketball Sleeveless Shirt Size XL Big Graphic.
Offer sent for Baja Joe Pullover Knit Hoodie Size L Black White Gray Drug Rug.
Offer sent for Vintage Rock and Folk Magazine David Bowie Cover April 1981 French Issue 171.
VTG White's of New England Metal Detectors Trucker Hat Watertown MA is below the provided floor price. No offer sent.
Offer sent for Vintage Barbie Fashion Avenue Sunglasses New In Bag Pink 90s.
Offer sent for SentrySafe Fire Safe Waterproof Lock Box Model H0100 Gray Heavy Metal 2 Keys.
Offer sent for Mattel Disney Pixar Cars Stunt Racers Chick Hicks Toy Car Tested Working M9684.
Offer sent for Vintage 90s Tommy Hilfiger Jeans Script Logo T Shirt Size L Red.
Offer sent for Cardinal Industries Ultimate Nickelodeon Trivia Game Complete In Tin 2002 VTG.
Justin Timberlake 20/20 Experience 2013 World Tour Shirt Size M is below the provided floor price. No offer sent.
Offer sent for VTG 90s Sports Specialties Boston College Eagles Snapback Hat Washed Reshaped.

TimeoutException: Message:
Stacktrace:
	GetHandleVerifier [0x00007FF608FDEEA2+31554]
	(No symbol) [0x00007FF608F57ED9]
	(No symbol) [0x00007FF608E1872A]
	(No symbol) [0x00007FF608E68434]
	(No symbol) [0x00007FF608E6853C]
	(No symbol) [0x00007FF608EAF6A7]
	(No symbol) [0x00007FF608E8D06F]
	(No symbol) [0x00007FF608EAC977]
	(No symbol) [0x00007FF608E8CDD3]
	(No symbol) [0x00007FF608E5A33B]
	(No symbol) [0x00007FF608E5AED1]
	GetHandleVerifier [0x00007FF6092E8B1D+3217341]
	GetHandleVerifier [0x00007FF609335AE3+3532675]
	GetHandleVerifier [0x00007FF60932B0E0+3489152]
	GetHandleVerifier [0x00007FF60908E776+750614]
	(No symbol) [0x00007FF608F6375F]
	(No symbol) [0x00007FF608F5EB14]
	(No symbol) [0x00007FF608F5ECA2]
	(No symbol) [0x00007FF608F4E16F]
	BaseThreadInitThunk [0x00007FFADD7A7374+20]
	RtlUserThreadStart [0x00007FFADDF1CC91+33]